apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: semantic-router
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - vllm-semantic-router-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: semantic-router-metrics
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: metrics
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__address__]
            target_label: instance
