apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-semantic-router-system

commonLabels:
  app.kubernetes.io/part-of: semantic-router
  app.kubernetes.io/component: observability

resources:
  - prometheus/rbac.yaml
  - prometheus/pvc.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - grafana/secret.yaml
  - grafana/pvc.yaml
  - grafana/configmap-provisioning.yaml
  - grafana/configmap-dashboard.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - dashboard/configmap.yaml
  - dashboard/deployment.yaml
  - dashboard/service.yaml
  - pipelines/deployment.yaml
  - openwebui/deployment.yaml
  - ingress.yaml

# Generate ConfigMaps from source files
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: openwebui-pipelines-config
    files:
      - vllm_semantic_router_pipe.py=../../../tools/openwebui-pipe/vllm_semantic_router_pipe.py
