//! Cross-language regression fixtures generated by actual sklearn training.
//! Regenerate with src/training/model_selection/ml_model_selection/tests/generate_native_fixtures.py.
use ml_semantic_router::{KMeansSelector, KNNSelector, SVMSelector};
use serde::Deserialize;
use std::collections::BTreeMap;

#[derive(Deserialize)]
struct Fixtures {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    artifact: serde_json::Value,
    queries: Vec<Vec<f64>>,
    expected: Vec<String>,
}

#[test]
fn python_exports_match_native_predictions_and_roundtrip() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/python_selectors.json")).unwrap();
    for case in fixtures.cases {
        let json = case.artifact.to_string();
        match case.artifact["algorithm"].as_str().unwrap() {
            "svm" => {
                let model = SVMSelector::from_json(&json).unwrap();
                let restored = SVMSelector::from_json(&model.to_json().unwrap()).unwrap();
                for (query, expected) in case.queries.iter().zip(&case.expected) {
                    assert_eq!(&model.select(query).unwrap(), expected, "{}", case.name);
                    assert_eq!(
                        &restored.select(query).unwrap(),
                        expected,
                        "{} roundtrip",
                        case.name
                    );
                }
                assert!(model.select(&[1.0]).is_err());
            }
            "knn" => {
                let model = KNNSelector::from_json(&json).unwrap();
                let restored = KNNSelector::from_json(&model.to_json().unwrap()).unwrap();
                for (query, expected) in case.queries.iter().zip(&case.expected) {
                    assert_eq!(&model.select(query).unwrap(), expected, "{}", case.name);
                    assert_eq!(
                        &restored.select(query).unwrap(),
                        expected,
                        "{} roundtrip",
                        case.name
                    );
                }
                assert!(model.select(&[1.0]).is_err());
            }
            algorithm => panic!("Unknown fixture algorithm: {algorithm}"),
        }
    }
}

#[test]
fn malformed_exports_fail_loading() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/python_selectors.json")).unwrap();
    for mut case in fixtures.cases {
        if case.artifact["algorithm"] == "svm" {
            case.artifact["svc"]["support_vectors"][0] = serde_json::json!([1.0]);
            assert!(SVMSelector::from_json(&case.artifact.to_string()).is_err());
        } else {
            case.artifact["labels"] = serde_json::json!(["only-one-label"]);
            assert!(KNNSelector::from_json(&case.artifact.to_string()).is_err());
        }
    }
}

#[derive(Deserialize)]
struct KMeansFixtures {
    cases: Vec<KMeansCase>,
    artifact_rejects: Vec<KMeansReject>,
}

#[derive(Deserialize)]
struct KMeansCase {
    name: String,
    artifact: serde_json::Value,
    queries: Vec<KMeansQuery>,
}

#[derive(Deserialize)]
struct KMeansQuery {
    vector: Vec<f64>,
    candidates: Option<Vec<String>>,
    cluster_id: Option<usize>,
    #[serde(default)]
    scores: BTreeMap<String, f64>,
    model: Option<String>,
    error: Option<String>,
}

#[derive(Deserialize)]
struct KMeansReject {
    reason: String,
    artifact: serde_json::Value,
}

type Mutation = (&'static str, fn(&mut serde_json::Value));

fn kmeans_fixtures() -> KMeansFixtures {
    serde_json::from_str(include_str!("fixtures/python_kmeans.json")).unwrap()
}

/// Python's KMeansModel.score: eligible candidates in set order, first maximum wins.
fn decide(
    model: &KMeansSelector,
    query: &KMeansQuery,
) -> Result<(usize, BTreeMap<String, f64>, String), String> {
    let scored = model
        .score(&query.vector)
        .map_err(|_| "invalid_query".to_string())?;
    let names = model.model_names();
    let eligible: Vec<usize> = (0..names.len())
        .filter(|&i| {
            query
                .candidates
                .as_ref()
                .is_none_or(|c| c.contains(&names[i]))
        })
        .collect();
    let mut best: Option<usize> = None;
    for &i in &eligible {
        if best.is_none_or(|b| scored.scores[i] > scored.scores[b]) {
            best = Some(i);
        }
    }
    let best = best.ok_or_else(|| "no_eligible_candidate".to_string())?;
    let scores = eligible
        .iter()
        .map(|&i| (names[i].clone(), scored.scores[i]))
        .collect();
    Ok((scored.cluster_id, scores, names[best].clone()))
}

#[test]
fn python_kmeans_v2_matches_native_cluster_scores_and_selection() {
    for case in kmeans_fixtures().cases {
        let model = KMeansSelector::from_json(&case.artifact.to_string()).unwrap();
        let restored = KMeansSelector::from_json(&model.to_json().unwrap()).unwrap();
        for (i, query) in case.queries.iter().enumerate() {
            let label = format!("{} query {i}", case.name);
            for selector in [&model, &restored] {
                match (&query.error, decide(selector, query)) {
                    (Some(want), Err(got)) => assert_eq!(&got, want, "{label}"),
                    (None, Ok((cluster, scores, winner))) => {
                        assert_eq!(Some(cluster), query.cluster_id, "{label}");
                        let bits = |m: &BTreeMap<String, f64>| {
                            m.iter()
                                .map(|(k, v)| (k.clone(), v.to_bits()))
                                .collect::<Vec<_>>()
                        };
                        assert_eq!(bits(&scores), bits(&query.scores), "{label}");
                        assert_eq!(Some(&winner), query.model.as_ref(), "{label}");
                        if query.candidates.is_none() {
                            assert_eq!(selector.select(&query.vector).unwrap(), winner, "{label}");
                        }
                    }
                    (want, got) => panic!("{label}: expected {want:?}, got {got:?}"),
                }
            }
        }
        // JSON cannot carry non-finite queries, so they are built here.
        let dim = case.queries[0].vector.len();
        for bad in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            let mut vector = vec![0.0; dim];
            vector[dim - 1] = bad;
            assert!(model.score(&vector).is_err(), "{} {bad}", case.name);
            assert!(model.select(&vector).is_err(), "{} {bad}", case.name);
        }
        assert!(model.score(&vec![0.0; dim - 1]).is_err(), "{}", case.name);
        assert!(model.score(&[]).is_err(), "{}", case.name);
    }
}

#[test]
fn python_kmeans_rejects_fail_native_loading() {
    let fixtures = kmeans_fixtures();
    assert_eq!(fixtures.artifact_rejects.len(), 7);
    for reject in &fixtures.artifact_rejects {
        assert!(
            KMeansSelector::from_json(&reject.artifact.to_string()).is_err(),
            "{} was accepted",
            reject.reason
        );
    }
    let valid = &fixtures.cases[0].artifact;
    let mutations: [Mutation; 7] = [
        ("format_version 0", |a| a["format_version"] = 0.into()),
        ("format_version string", |a| {
            a["format_version"] = "2".into()
        }),
        ("short centroid", |a| {
            a["centroids"][0].as_array_mut().unwrap().pop();
        }),
        ("long centroid", |a| {
            a["centroids"][1].as_array_mut().unwrap().push(0.0.into())
        }),
        ("zero dim", |a| a["feature"]["dim"] = 0.into()),
        ("missing scores row", |a| {
            a["scores"].as_array_mut().unwrap().pop();
        }),
        ("fractional support", |a| a["support"][0][0] = 1.5.into()),
    ];
    for (reason, mutate) in mutations {
        let mut broken = valid.clone();
        mutate(&mut broken);
        assert!(
            KMeansSelector::from_json(&broken.to_string()).is_err(),
            "{reason} was accepted"
        );
    }
    // Overflowing literals are how a non-finite value would reach the loader.
    let overflow = valid
        .to_string()
        .replacen("\"centroids\":[[", "\"centroids\":[[1e999,", 1);
    assert!(KMeansSelector::from_json(&overflow).is_err());
}
