//! Cross-language regression fixtures generated by actual sklearn training.
//! Regenerate with src/training/model_selection/ml_model_selection/tests/generate_native_fixtures.py.
use ml_semantic_router::{KNNSelector, SVMSelector};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    artifact: serde_json::Value,
    queries: Vec<Vec<f64>>,
    expected: Vec<String>,
}

#[test]
fn python_exports_match_native_predictions_and_roundtrip() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/python_selectors.json")).unwrap();
    for case in fixtures.cases {
        let json = case.artifact.to_string();
        match case.artifact["algorithm"].as_str().unwrap() {
            "svm" => {
                let model = SVMSelector::from_json(&json).unwrap();
                let restored = SVMSelector::from_json(&model.to_json().unwrap()).unwrap();
                for (query, expected) in case.queries.iter().zip(&case.expected) {
                    assert_eq!(&model.select(query).unwrap(), expected, "{}", case.name);
                    assert_eq!(
                        &restored.select(query).unwrap(),
                        expected,
                        "{} roundtrip",
                        case.name
                    );
                }
                assert!(model.select(&[1.0]).is_err());
            }
            "knn" => {
                let model = KNNSelector::from_json(&json).unwrap();
                let restored = KNNSelector::from_json(&model.to_json().unwrap()).unwrap();
                for (query, expected) in case.queries.iter().zip(&case.expected) {
                    assert_eq!(&model.select(query).unwrap(), expected, "{}", case.name);
                    assert_eq!(
                        &restored.select(query).unwrap(),
                        expected,
                        "{} roundtrip",
                        case.name
                    );
                }
                assert!(model.select(&[1.0]).is_err());
            }
            algorithm => panic!("Unknown fixture algorithm: {algorithm}"),
        }
    }
}

#[test]
fn malformed_exports_fail_loading() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/python_selectors.json")).unwrap();
    for mut case in fixtures.cases {
        if case.artifact["algorithm"] == "svm" {
            case.artifact["svc"]["support_vectors"][0] = serde_json::json!([1.0]);
            assert!(SVMSelector::from_json(&case.artifact.to_string()).is_err());
        } else {
            case.artifact["labels"] = serde_json::json!(["only-one-label"]);
            assert!(KNNSelector::from_json(&case.artifact.to_string()).is_err());
        }
    }
}
