apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: vllm-semantic-router-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: semantic-router-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
