apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: vllm-semantic-router-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: semantic-router-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-semantic-router
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: semantic-router-stack
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-semantic-router
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: semantic-router-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-semantic-router
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: vllm-semantic-router-system
