apiVersion: v1
kind: PersistentVolume
metadata:
  name: semantic-router-models-pv
  labels:
    app: semantic-router
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/hostpath-provisioner/models
    type: DirectoryOrCreate
