import { useEffect, useRef, useState } from 'react'

import styles from './OpenClawPage.module.css'
import type {
  ContainerConfig,
  IdentityConfig,
  ProvisionResponse,
  SkillTemplate,
  TeamProfile,
} from './OpenClawPageSupport'

interface OpenClawWorkerDeployStepProps {
  container: ContainerConfig
  identity: IdentityConfig
  onProvision: () => void
  onSwitchToStatus: () => void
  provisionLoading: boolean
  provisionResult: ProvisionResponse | null
  selectedSkills: string[]
  selectedTeam: TeamProfile | null
  skills: SkillTemplate[]
  teamMissing: boolean
  onDone?: () => void
}

export function OpenClawWorkerDeployStep({
  identity,
  selectedSkills,
  skills,
  container,
  selectedTeam,
  teamMissing,
  onProvision,
  provisionLoading,
  provisionResult,
  onSwitchToStatus,
  onDone,
}: OpenClawWorkerDeployStepProps) {
  const [copied, setCopied] = useState('')
  const [showCommands, setShowCommands] = useState(false)
  const [copyError, setCopyError] = useState('')
  const copyTimerRef = useRef<number | null>(null)

  useEffect(
    () => () => {
      if (copyTimerRef.current !== null) window.clearTimeout(copyTimerRef.current)
    },
    [],
  )

  const copyToClipboard = (text: string, label: string) => {
    void navigator.clipboard.writeText(text).then(
      () => {
        setCopyError('')
        setCopied(label)
        if (copyTimerRef.current !== null) window.clearTimeout(copyTimerRef.current)
        copyTimerRef.current = window.setTimeout(() => setCopied(''), 2000)
      },
      () => setCopyError('Clipboard access was denied. Select and copy the command manually.'),
    )
  }

  const selectedSkillNames = skills.filter((skill) => selectedSkills.includes(skill.id))

  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepTitle}>Step 4: Review & Deploy</h2>
      <p className={styles.stepDescription}>
        Review your configuration, then provision and start the OpenClaw container.
      </p>

      {teamMissing && (
        <div className={styles.errorAlert}>
          <span>Team selection is required before deployment.</span>
        </div>
      )}

      <div className={styles.summaryGrid}>
        <div className={styles.summaryCard}>
          <div className={styles.summaryCardTitle}>Identity</div>
          <div className={styles.summaryCardContent}>
            <strong>
              {identity.emoji} {identity.name || '(unnamed)'}
            </strong>
            <br />
            {identity.role || '(no role)'}
            <br />
            <span className={styles.summaryMuted}>{identity.vibe}</span>
          </div>
        </div>
        <div className={styles.summaryCard}>
          <div className={styles.summaryCardTitle}>Team</div>
          <div className={styles.summaryCardContent}>
            <strong>{selectedTeam?.name || '(not selected)'}</strong>
            <br />
            {selectedTeam?.role || 'No role set'}
            <br />
            <span className={styles.summaryMuted}>{selectedTeam?.vibe || 'No vibe set'}</span>
          </div>
        </div>
        <div className={styles.summaryCard}>
          <div className={styles.summaryCardTitle}>Skills ({selectedSkills.length})</div>
          <div className={styles.summarySkillList}>
            {selectedSkillNames.map((skill) => (
              <span key={skill.id} className={styles.summarySkillBadge}>
                {skill.emoji} {skill.name}
              </span>
            ))}
            {selectedSkills.length === 0 && (
              <span className={styles.summaryMuted}>No skills selected</span>
            )}
          </div>
        </div>
        <div className={styles.summaryCard}>
          <div className={styles.summaryCardTitle}>Container</div>
          <div className={styles.summaryCardContent}>
            <strong>Auto-generated by backend</strong> :{container.gatewayPort || 'auto'}
            <br />
            Image: {container.baseImage}
            <br />
            Network: {container.networkMode}
          </div>
        </div>
        <div className={styles.summaryCard}>
          <div className={styles.summaryCardTitle}>Model & Memory</div>
          <div className={styles.summaryCardContent}>
            Model: {container.modelName} via SR
            <br />
            Memory:{' '}
            {container.memoryBackend === 'remote'
              ? `Remote embeddings${container.memoryBaseUrl ? ` (${container.memoryBaseUrl})` : ''}`
              : 'Built-in'}
            <br />
            Browser: {container.browserEnabled ? 'Enabled' : 'Disabled'}
          </div>
        </div>
      </div>

      {!provisionResult && (
        <button
          type="button"
          className={styles.btnSuccess}
          onClick={onProvision}
          disabled={provisionLoading || teamMissing}
        >
          {provisionLoading ? 'Provisioning & starting container...' : 'Provision & Start'}
        </button>
      )}

      {provisionResult?.success && (
        <div className={styles.successCard}>
          <div className={styles.successIcon}>
            <svg
              width="48"
              height="48"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#22c55e"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <circle cx="12" cy="12" r="10" />
              <polyline points="16 8 10 16 7 13" />
            </svg>
          </div>
          <div className={styles.successTitle}>Container Started</div>
          <div className={styles.successMessage}>
            {provisionResult.message}
            {provisionResult.containerId && (
              <>
                <br />
                <code style={{ fontSize: '0.75rem' }}>
                  {provisionResult.containerId.slice(0, 12)}
                </code>
              </>
            )}
          </div>

          <div className={styles.successActions}>
            <button type="button" className={styles.btnPrimary} onClick={onSwitchToStatus}>
              Go to Claw Dashboard
            </button>
            {onDone ? (
              <button type="button" className={styles.btnSecondary} onClick={onDone}>
                Done
              </button>
            ) : null}
          </div>

          {copyError ? (
            <div className={styles.confirmInlineError} role="alert">
              {copyError}
            </div>
          ) : null}
          <div className={styles.commandReference}>
            <button
              type="button"
              onClick={() => setShowCommands(!showCommands)}
              className={styles.commandDisclosure}
              aria-expanded={showCommands}
            >
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                className={
                  showCommands ? styles.commandDisclosureIconOpen : styles.commandDisclosureIcon
                }
              >
                <polyline points="9 18 15 12 9 6" />
              </svg>
              Docker commands reference
            </button>

            {showCommands && (
              <>
                {provisionResult.dockerCmd && (
                  <div className={styles.codePreview}>
                    <div className={styles.codePreviewHeader}>
                      <span className={styles.codePreviewLabel}>Docker Run Command</span>
                      <button
                        type="button"
                        className={styles.codePreviewCopy}
                        onClick={() => copyToClipboard(provisionResult.dockerCmd, 'docker')}
                      >
                        {copied === 'docker' ? 'Copied!' : 'Copy'}
                      </button>
                    </div>
                    <pre className={styles.codePreviewContent}>{provisionResult.dockerCmd}</pre>
                  </div>
                )}

                {provisionResult.composeYaml && (
                  <div className={styles.codePreview}>
                    <div className={styles.codePreviewHeader}>
                      <span className={styles.codePreviewLabel}>Docker Compose YAML</span>
                      <button
                        type="button"
                        className={styles.codePreviewCopy}
                        onClick={() => copyToClipboard(provisionResult.composeYaml, 'compose')}
                      >
                        {copied === 'compose' ? 'Copied!' : 'Copy'}
                      </button>
                    </div>
                    <pre className={styles.codePreviewContent}>{provisionResult.composeYaml}</pre>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
