"""Specs and decisions of the card-fix revisions of five Decision 2.0 repositories (round 3).

User job 2026-10-02 03:04 UTC+8 (release worker 4c0a68cd): on the Jev Decision Index charts every Decision 2.0
point follows the board's served-parameter convention for its base (the board's 1.0 points and peers already do),
and the Index footnote discloses the row-level training-data audit. Both are the defaults of v2.release.card_index
and v2.release.card_assets; the at-a-glance table keeps the loaded parameter count. Kai 0.6B, Eos 0.8B, Sol 2B,
Nox 4B and Vega 27B get card-only revisions; Lux 9B is left to its successor release.

Each spec is the round-2 product spec with card.index and card.assets re-pinned to the regenerated private inputs
and gate_receipt = the new decision. Each decision carries the superseded round-2 decision's judgement forward and
changes only the action, the rationale and the supersedes chain.

Run from src/training/decision2 (the digests come from the private inputs, given on the command line):

  python3 v2/release/records/dev2-card3-2026-10-02/ops/make_card3.py --pins PINS.json [--check]

PINS.json: {"index_sha256": ..., "assets": {"<tier>": receipt_sha256, ...}}.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import sys
from pathlib import Path

RECORDS = Path("v2/release/records")
SPECS = Path("v2/release/specs")
ROUND2 = RECORDS / "dev2-card2-2026-10-02"
OUT = RECORDS / "dev2-card3-2026-10-02"
DECISIONS = "/data/dev2/runs/release/decisions"
PRIVATE = "/data/dev2/private/release/card3"
INDEX = f"{PRIVATE}/decision-index-card.json"
ORG = "llm-semantic-router"
DECIDED_BY = (
    "coordinator (parent agent), Decision 2.0 program: the user's card fix of 2026-10-02 03:04 UTC+8 (the Jev "
    "Decision Index charts plot Decision 2.0 with the board's served-parameter convention for the same base; the "
    "Index footnote adds the row-level training-data audit), card-only revisions of Kai 0.6B, Eos 0.8B, Sol 2B, "
    "Nox 4B and Vega 27B; Lux 9B is regenerated by its successor release"
)
PREPARED_BY = "Decision 2.0 release engineering, release worker 4c0a68cd (worktree vllm-sr-dev2-automap)"
DECIDED_UTC = "2026-10-01T19:04:00Z"
TIERS = (
    {"tier": "0.6B", "key": "0p6b", "codename": "Kai"},
    {"tier": "0.8B", "key": "0p8b", "codename": "Eos"},
    {"tier": "2B", "key": "2b", "codename": "Sol"},
    {"tier": "4B", "key": "4b", "codename": "Nox"},
    {"tier": "27B", "key": "27b", "codename": "Vega"},
)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def spec_for(t: dict, pins: dict) -> dict:
    source = SPECS / f"dev2-{t['key']}-product.json"
    old = json.loads(source.read_text(encoding="utf-8"))
    name = old["model_name"]
    assert name == f"Decision-2.0-{t['codename']}-{t['tier']}", t
    spec = copy.deepcopy(old)
    card = spec["card"]
    card["index"] = {"path": INDEX, "sha256": pins["index_sha256"]}
    card["assets"] = {
        "dir": f"{PRIVATE}/{t['key']}",
        "receipt_sha256": pins["assets"][t["tier"]],
    }
    spec["gate_receipt"] = f"{DECISIONS}/{name}.decision.card3.json"
    spec["_release"] = {
        "card_fix": (
            "Card-only revision (user card fix 2026-10-02 03:04 UTC+8, release worker 4c0a68cd): the Jev Decision "
            "Index charts plot every Decision 2.0 point at the board's served-parameter count for its base "
            "(card_index.BOARD_BASES), as the board does for Decision 1.0 and the public entrants, and the Index "
            "footnote is card_index.FOOTNOTE with the row-level training-data audit. card.index and card.assets "
            "pin the regenerated private Index input and assets. Everything else, the at-a-glance table's loaded "
            "parameter count included, is the round-2 product card."
        ),
        "replaces_spec": {"spec": source.as_posix(), "sha256": sha(source)},
        "previous": old.get("_release"),
    }
    return spec


def decision_for(t: dict, spec_sha: str) -> dict:
    name = f"Decision-2.0-{t['codename']}-{t['tier']}"
    old_path = ROUND2 / f"{name}.decision.card2.json"
    gate_path = ROUND2 / t["key"] / "release/receipts/gate.json"
    old = json.loads(old_path.read_text(encoding="utf-8"))
    old_sha = sha(old_path)
    assert old["status"] == "final", t
    gate = json.loads(gate_path.read_text(encoding="utf-8"))
    assert gate["decision_sha256"] == old_sha and gate["model_name"] == name, t
    repo = gate["repo_id"]
    new = copy.deepcopy(old)
    new.update(
        {
            "decided_by": DECIDED_BY,
            "prepared_by": PREPARED_BY,
            "decided_utc": DECIDED_UTC,
            "action": (
                f"Card-only revision of the private repository {repo}: README.md (Index footnote) and "
                "assets/index-pareto.png and assets/index-areas.png are regenerated. Every other file is "
                f"byte-identical to the released revision {gate['revision']}. The collection is not changed; "
                "everything stays private."
            ),
            "rationale": (
                f"The release judgement of the superseded final decision {old_sha[:8]}… stands unchanged: the same "
                f"identity {old['identity']['model_sha256'][:8]}, scored report, paired comparison, calibration and "
                "licence decision. Only the Index charts' size axis convention, the Index footnote and the "
                "manifest digests change; release.sh checks the native examples, the card's Transformers example "
                "before upload, after the real download and from the Hub in fresh environments under "
                "Transformers 5.17 and 5.18, the card structure and every card link."
            ),
            "previous_rationale": old["rationale"],
            "card_revision": {
                "kind": "card-index-convention",
                "spec": f"v2/release/specs/dev2-{t['key']}-card3.json",
                "spec_sha256": spec_sha,
            },
            "supersedes": {
                "final_sha256": old_sha,
                "released_as": f"{repo}@{gate['revision']}",
                "released_manifest_sha256": gate["manifest_sha256"],
                "released_gate_sha256": sha(gate_path),
                "earlier": old.get("supersedes"),
            },
        }
    )
    return new


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pins", type=Path, required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    pins = json.loads(args.pins.read_text())
    problems = []
    for t in TIERS:
        spec_text = json.dumps(spec_for(t, pins), ensure_ascii=False, indent=2) + "\n"
        spec_sha = hashlib.sha256(spec_text.encode()).hexdigest()
        decision_text = (
            json.dumps(decision_for(t, spec_sha), ensure_ascii=False, indent=2) + "\n"
        )
        name = f"Decision-2.0-{t['codename']}-{t['tier']}"
        for path, text in (
            (SPECS / f"dev2-{t['key']}-card3.json", spec_text),
            (OUT / f"{name}.decision.card3.json", decision_text),
        ):
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != text:
                    problems.append(f"{path}: differs from the derivation")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
            print(path, hashlib.sha256(text.encode()).hexdigest())
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
