// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for AnswerError.
const (
	DeadlineExceeded   AnswerError = "deadline_exceeded"
	InvalidModelOutput AnswerError = "invalid_model_output"
	InvalidQuestion    AnswerError = "invalid_question"
	MaxLengthExceeded  AnswerError = "max_length_exceeded"
	Unavailable        AnswerError = "unavailable"
)

// Defines values for ErrorResponseErrorCode.
const (
	InternalError   ErrorResponseErrorCode = "internal_error"
	InvalidRequest  ErrorResponseErrorCode = "invalid_request"
	ModelNotFound   ErrorResponseErrorCode = "model_not_found"
	NotReady        ErrorResponseErrorCode = "not_ready"
	Overloaded      ErrorResponseErrorCode = "overloaded"
	RequestTooLarge ErrorResponseErrorCode = "request_too_large"
)

// Defines values for GoldenStatusStatus.
const (
	GoldenStatusStatusFailed     GoldenStatusStatus = "failed"
	GoldenStatusStatusMatched    GoldenStatusStatus = "matched"
	GoldenStatusStatusPending    GoldenStatusStatus = "pending"
	GoldenStatusStatusUnverified GoldenStatusStatus = "unverified"
)

// Defines values for HealthStatus.
const (
	HealthStatusAlive    HealthStatus = "alive"
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusFailed   HealthStatus = "failed"
	HealthStatusLoading  HealthStatus = "loading"
	HealthStatusReady    HealthStatus = "ready"
	HealthStatusStarting HealthStatus = "starting"
	HealthStatusWarming  HealthStatus = "warming"
)

// Defines values for ProfileInfoNumerics.
const (
	Approximate ProfileInfoNumerics = "approximate"
	Exact       ProfileInfoNumerics = "exact"
)

// Answer One answer. Choice: choice, probabilities, confidence. Noul: noul (P(true)). Score: score (the expected
// level), probabilities, confidence, legend. A failed question has only type and error.
type Answer struct {
	Choice        *string             `json:"choice,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Error         *AnswerError        `json:"error,omitempty"`
	Legend        *map[string]string  `json:"legend,omitempty"`
	Noul          *float64            `json:"noul,omitempty"`
	Probabilities *map[string]float64 `json:"probabilities,omitempty"`
	Score         *float64            `json:"score,omitempty"`
	Type          *string             `json:"type"`
}

// AnswerError defines model for Answer.Error.
type AnswerError string

// ChoiceOption defines model for ChoiceOption.
type ChoiceOption struct {
	// Description Text, an object, an array or null.
	Description *interface{} `json:"description"`
	Key         string       `json:"key"`
}

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	// Model Served model ID. Optional while a runtime serves one model.
	Model   *string         `json:"model,omitempty"`
	Options *RequestOptions `json:"options,omitempty"`

	// Questions Named questions; answers keep this order.
	Questions map[string]Question `json:"questions"`

	// State The context the questions are about; text, an object or an array of JSON values.
	State interface{} `json:"state"`
}

// DecisionResponse defines model for DecisionResponse.
type DecisionResponse struct {
	Answers map[string]Answer `json:"answers"`
	Meta    *ResponseMeta     `json:"meta,omitempty"`
	Model   string            `json:"model"`
	Usage   Usage             `json:"usage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// GoldenStatus defines model for GoldenStatus.
type GoldenStatus struct {
	Checked   *int               `json:"checked,omitempty"`
	Matched   *int               `json:"matched,omitempty"`
	Reference *string            `json:"reference"`
	Status    GoldenStatusStatus `json:"status"`
}

// GoldenStatusStatus defines model for GoldenStatus.Status.
type GoldenStatusStatus string

// Health defines model for Health.
type Health struct {
	Model  *string      `json:"model"`
	Reason *string      `json:"reason"`
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ModelCard defines model for ModelCard.
type ModelCard struct {
	Accelerator          *string        `json:"accelerator,omitempty"`
	AcceleratorValidated *bool          `json:"accelerator_validated,omitempty"`
	Device               *string        `json:"device,omitempty"`
	Dtype                *string        `json:"dtype,omitempty"`
	Engine               *string        `json:"engine,omitempty"`
	Family               string         `json:"family"`
	Golden               *GoldenStatus  `json:"golden,omitempty"`
	Id                   string         `json:"id"`
	Licence              *string        `json:"licence"`
	Limits               *ModelLimits   `json:"limits,omitempty"`
	ManifestSha256       *string        `json:"manifest_sha256,omitempty"`
	ModelSha256          *string        `json:"model_sha256,omitempty"`
	Object               string         `json:"object"`
	OwnedBy              *string        `json:"owned_by,omitempty"`
	Parameters           *int           `json:"parameters,omitempty"`
	Plugins              *[]PluginInfo  `json:"plugins,omitempty"`
	Profile              *string        `json:"profile,omitempty"`
	Profiles             *[]ProfileInfo `json:"profiles,omitempty"`
	QuestionTypes        *[]string      `json:"question_types,omitempty"`
	Ready                bool           `json:"ready"`
	Repo                 *string        `json:"repo"`
	Revision             *string        `json:"revision"`
	Surfaces             []string       `json:"surfaces"`
}

// ModelLimits defines model for ModelLimits.
type ModelLimits struct {
	MaxInputTokens *int `json:"max_input_tokens,omitempty"`
	MaxLevels      *int `json:"max_levels,omitempty"`
	MaxOptions     *int `json:"max_options,omitempty"`
	MinLevels      *int `json:"min_levels,omitempty"`
	MinOptions     *int `json:"min_options,omitempty"`
}

// ModelList defines model for ModelList.
type ModelList struct {
	Data   []ModelCard `json:"data"`
	Object string      `json:"object"`
}

// PluginInfo defines model for PluginInfo.
type PluginInfo struct {
	Distribution *string `json:"distribution"`
	Group        string  `json:"group"`
	Name         string  `json:"name"`
	Version      *string `json:"version"`
}

// ProfileInfo defines model for ProfileInfo.
type ProfileInfo struct {
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Numerics    ProfileInfoNumerics `json:"numerics"`
}

// ProfileInfoNumerics defines model for ProfileInfo.Numerics.
type ProfileInfoNumerics string

// Question defines model for Question.
type Question struct {
	// Choices Ordered Choice or Noul options, an alternative to a criteria object.
	Choices *[]ChoiceOption `json:"choices,omitempty"`

	// Criteria System One criteria. Choice: an object of 2..255 option keys to descriptions (descriptions may be
	// null). Noul: an optional object with only false and true. Score: an ordered list of 2..10 level
	// descriptions.
	Criteria *interface{} `json:"criteria,omitempty"`

	// Instructions The question; non-empty text, an object or an array.
	Instructions interface{} `json:"instructions"`

	// Levels Ordered Score level descriptions, an alternative to a criteria list.
	Levels *[]interface{} `json:"levels,omitempty"`

	// Type choice, noul or score. Unknown types are answered with invalid_question.
	Type string `json:"type"`
}

// RequestOptions defines model for RequestOptions.
type RequestOptions struct {
	// DeadlineMs Questions not started by the deadline return deadline_exceeded.
	DeadlineMs *float64 `json:"deadline_ms,omitempty"`

	// Profile exact, or the profile the server enabled.
	Profile *string `json:"profile,omitempty"`

	// ReturnMeta Include meta in the response (default false).
	ReturnMeta *bool `json:"return_meta,omitempty"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Accelerator *string  `json:"accelerator,omitempty"`
	ComputeMs   *float64 `json:"compute_ms,omitempty"`
	Device      *string  `json:"device,omitempty"`
	Engine      *string  `json:"engine,omitempty"`
	ModelSha256 *string  `json:"model_sha256,omitempty"`
	Numerics    *string  `json:"numerics,omitempty"`
	Profile     *string  `json:"profile,omitempty"`
	QueueMs     *float64 `json:"queue_ms,omitempty"`

	// Revision The 40-hex Hub revision; null for a local package directory.
	Revision *string `json:"revision"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// Error defines model for Error.
type Error = ErrorResponse

// CreateDecisionsJSONRequestBody defines body for CreateDecisions for application/json ContentType.
type CreateDecisionsJSONRequestBody = DecisionRequest

// CreateSystemOneJSONRequestBody defines body for CreateSystemOne for application/json ContentType.
type CreateSystemOneJSONRequestBody = DecisionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLiveness request
	GetLiveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMetrics request
	GetMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDecisionsWithBody request with any body
	CreateDecisionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDecisions(ctx context.Context, body CreateDecisionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSystemOneWithBody request with any body
	CreateSystemOneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSystemOne(ctx context.Context, body CreateSystemOneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLiveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLivenessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMetricsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDecisionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDecisionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDecisions(ctx context.Context, body CreateDecisionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDecisionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSystemOneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSystemOneRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSystemOne(ctx context.Context, body CreateSystemOneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSystemOneRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLivenessRequest generates requests for GetLiveness
func NewGetLivenessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health/live")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMetricsRequest generates requests for GetMetrics
func NewGetMetricsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metrics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDecisionsRequest calls the generic CreateDecisions builder with application/json body
func NewCreateDecisionsRequest(server string, body CreateDecisionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDecisionsRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDecisionsRequestWithBody generates requests for CreateDecisions with any type of body
func NewCreateDecisionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/decisions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateSystemOneRequest calls the generic CreateSystemOne builder with application/json body
func NewCreateSystemOneRequest(server string, body CreateSystemOneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSystemOneRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateSystemOneRequestWithBody generates requests for CreateSystemOne with any type of body
func NewCreateSystemOneRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/systemone")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetLivenessWithResponse request
	GetLivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLivenessResponse, error)

	// GetMetricsWithResponse request
	GetMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMetricsResponse, error)

	// CreateDecisionsWithBodyWithResponse request with any body
	CreateDecisionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDecisionsResponse, error)

	CreateDecisionsWithResponse(ctx context.Context, body CreateDecisionsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDecisionsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// CreateSystemOneWithBodyWithResponse request with any body
	CreateSystemOneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSystemOneResponse, error)

	CreateSystemOneWithResponse(ctx context.Context, body CreateSystemOneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSystemOneResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
	JSON503      *Health
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLivenessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r GetLivenessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLivenessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDecisionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DecisionResponse
	JSON400      *Error
	JSON404      *Error
	JSON413      *Error
	JSON429      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r CreateDecisionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDecisionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelList
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateSystemOneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DecisionResponse
	JSON400      *Error
	JSON404      *Error
	JSON413      *Error
	JSON429      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r CreateSystemOneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSystemOneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetLivenessWithResponse request returning *GetLivenessResponse
func (c *ClientWithResponses) GetLivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLivenessResponse, error) {
	rsp, err := c.GetLiveness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLivenessResponse(rsp)
}

// GetMetricsWithResponse request returning *GetMetricsResponse
func (c *ClientWithResponses) GetMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMetricsResponse, error) {
	rsp, err := c.GetMetrics(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMetricsResponse(rsp)
}

// CreateDecisionsWithBodyWithResponse request with arbitrary body returning *CreateDecisionsResponse
func (c *ClientWithResponses) CreateDecisionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDecisionsResponse, error) {
	rsp, err := c.CreateDecisionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDecisionsResponse(rsp)
}

func (c *ClientWithResponses) CreateDecisionsWithResponse(ctx context.Context, body CreateDecisionsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDecisionsResponse, error) {
	rsp, err := c.CreateDecisions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDecisionsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// CreateSystemOneWithBodyWithResponse request with arbitrary body returning *CreateSystemOneResponse
func (c *ClientWithResponses) CreateSystemOneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSystemOneResponse, error) {
	rsp, err := c.CreateSystemOneWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSystemOneResponse(rsp)
}

func (c *ClientWithResponses) CreateSystemOneWithResponse(ctx context.Context, body CreateSystemOneJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSystemOneResponse, error) {
	rsp, err := c.CreateSystemOne(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSystemOneResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetLivenessResponse parses an HTTP response from a GetLivenessWithResponse call
func ParseGetLivenessResponse(rsp *http.Response) (*GetLivenessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLivenessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMetricsResponse parses an HTTP response from a GetMetricsWithResponse call
func ParseGetMetricsResponse(rsp *http.Response) (*GetMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateDecisionsResponse parses an HTTP response from a CreateDecisionsWithResponse call
func ParseCreateDecisionsResponse(rsp *http.Response) (*CreateDecisionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDecisionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DecisionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateSystemOneResponse parses an HTTP response from a CreateSystemOneWithResponse call
func ParseCreateSystemOneResponse(rsp *http.Response) (*CreateSystemOneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSystemOneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DecisionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
