package soak

var prompts = []string{
	"What is 2+2?",
	"Summarize the difference between TCP and UDP.",
	"Write a haiku about garbage collection.",
	"Explain what a B-tree is and when a database would prefer it over a hash index.",
	"Translate 'the weather is fine today' into French.",
	"What causes a memory leak in a long-running Go service?",
	"Give me three ideas for reducing p99 latency in a request-scoped RPC path.",
	"Who wrote The Brothers Karamazov?",
	"Derive the closed form of the sum of the first n integers and show the induction step.",
	"How does a bloom filter trade accuracy for space, and what is the false positive formula?",
	"List the SI base units.",
	"Explain the CAP theorem to someone who has never operated a distributed system, using a concrete example involving two data centers separated by a partition.",
	"What is the difference between a mutex and a semaphore?",
	"Refactor advice: I have a 600 line function that parses config, validates it, and starts three servers. Where do I cut it?",
	"Name the seven layers of the OSI model.",
	"Why is floating point addition not associative? Show a small example.",
	"Draft a two sentence status update saying the migration slipped by a week.",
	"Compare gradient descent with Newton's method in terms of convergence rate and per-step cost.",
	"What is 17 percent of 240?",
	"Explain how TLS session resumption works and why it matters for connection-heavy workloads.",
	"Give a regular expression that matches an RFC 5322 addr-spec, and then explain why you should not use it.",
	"What does the Linux OOM killer score actually measure?",
	"Describe the tradeoffs between arena allocation and per-object allocation for a request-scoped workload with a strict tail latency budget.",
	"Convert 98.6 degrees Fahrenheit to Celsius.",
	"When would you choose a columnar storage format over row storage?",
	"Explain backpressure in streaming systems and name two ways to implement it.",
	"What is the halting problem?",
	"Write a short function signature review checklist for a Go code reviewer who cares about allocation behavior, context propagation, and error wrapping.",
	"How do consistent hashing rings handle node removal?",
	"Summarize the tradeoffs of running an LLM router as a sidecar versus a standalone gateway filter.",
}
