// Command trainingcontract generates schema and TypeScript from the canonical Go contract.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/invopop/jsonschema"

	c "github.com/vllm-project/semantic-router/src/semantic-router/pkg/trainingcontract"
)

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail on generated drift")
	flag.Parse()
	schema := (&jsonschema.Reflector{Anonymous: true}).Reflect(c.Catalog{})
	data, err := json.MarshalIndent(schema, "", "  ")
	must(err)
	write(*root, "src/semantic-router/pkg/trainingcontract/training-v1.schema.json", append(data, '\n'), *check)
	types := map[string]reflect.Type{}
	var collect func(reflect.Type)
	collect = func(t reflect.Type) {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice:
			collect(t.Elem())
			return
		case reflect.Map:
			collect(t.Elem())
			return
		}
		if t.PkgPath() != reflect.TypeOf(c.Catalog{}).PkgPath() {
			return
		}
		if _, ok := types[t.Name()]; ok {
			return
		}
		types[t.Name()] = t
		if t.Kind() == reflect.Struct {
			for i := 0; i < t.NumField(); i++ {
				collect(t.Field(i).Type)
			}
		}
	}
	collect(reflect.TypeOf(c.Catalog{}))
	var out strings.Builder
	out.WriteString("// Code generated by tools/codegen/trainingcontract. DO NOT EDIT.\n")
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		t := types[name]
		if t.Kind() != reflect.Struct {
			values := reflect.Zero(t).Interface().(interface {
				JSONSchema() *jsonschema.Schema
			}).JSONSchema().Enum
			parts := []string{}
			for _, v := range values {
				b, _ := json.Marshal(v)
				parts = append(parts, string(b))
			}
			fmt.Fprintf(&out, "export type %s = %s\n\n", name, strings.Join(parts, " | "))
			continue
		}
		if name == "Profile" {
			fmt.Fprintf(&out, "export type Profile =\n  | { target_contract: %q; selector: SelectorProfile }\n  | { target_contract: %q; classifier: ClassifierProfile }\n  | { target_contract: %q; spans: SpanProfile }\n\n", c.Selector, c.LabelScores, c.Spans)
			continue
		}
		fmt.Fprintf(&out, "export interface %s {\n", name)
		var fields func(reflect.Type)
		fields = func(t reflect.Type) {
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if f.Anonymous {
					fields(f.Type)
					continue
				}
				tag := strings.Split(f.Tag.Get("json"), ",")
				optional := ""
				if len(tag) > 1 && tag[1] == "omitempty" {
					optional = "?"
				}
				typ := tsType(f.Type)
				var enum []string
				for _, constraint := range strings.Split(f.Tag.Get("jsonschema"), ",") {
					if value, ok := strings.CutPrefix(constraint, "enum="); ok {
						enum = append(enum, fmt.Sprintf("%q", value))
					}
				}
				if len(enum) > 0 {
					typ = strings.Join(enum, " | ")
				}
				if definition := schema.Definitions[t.Name()]; definition != nil {
					if property, ok := definition.Properties.Get(tag[0]); ok && len(property.Enum) > 0 {
						enum = nil
						for _, value := range property.Enum {
							encoded, err := json.Marshal(value)
							must(err)
							enum = append(enum, string(encoded))
						}
						typ = strings.Join(enum, " | ")
					}
				}
				fmt.Fprintf(&out, "  %s%s: %s\n", tag[0], optional, typ)
			}
		}
		fields(t)
		out.WriteString("}\n\n")
	}
	write(*root, "dashboard/frontend/src/generated/trainingContract.ts", []byte(strings.TrimRight(out.String(), "\n")+"\n"), *check)
}

func tsType(t reflect.Type) string {
	if t == reflect.TypeOf(time.Time{}) {
		return "string"
	}
	if t.Name() != "" && t.PkgPath() != "" {
		return t.Name()
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem())
	case reflect.Slice:
		return "Array<" + tsType(t.Elem()) + ">"
	case reflect.Map:
		return "Record<string, " + tsType(t.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	default:
		return "number"
	}
}

func write(root, path string, data []byte, check bool) {
	path = filepath.Join(root, path)
	if check {
		existing, err := os.ReadFile(path)
		must(err)
		if !bytes.Equal(existing, data) {
			panic("generated contract drift: " + path)
		}
		return
	}
	must(os.WriteFile(path, data, 0o644))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
