---
queue_rules:
  - name: default
    queue_conditions:
      - base = main
      - or:
          - check-success = test-and-build
          - check-skipped = test-and-build
      - or:
          - check-success = Lint
          - check-skipped = Lint
      - or:
          - check-success = Unit Tests
          - check-skipped = Unit Tests
      - or:
          - check-success = Verify Manifests
          - check-skipped = Verify Manifests
      - or:
          - check-success = Validate OLM Bundle
          - check-skipped = Validate OLM Bundle
    merge_conditions:
      - base = main
      - or:
          - check-success = test-and-build
          - check-skipped = test-and-build
      - or:
          - check-success = Lint
          - check-skipped = Lint
      - or:
          - check-success = Unit Tests
          - check-skipped = Unit Tests
      - or:
          - check-success = Verify Manifests
          - check-skipped = Verify Manifests
      - or:
          - check-success = Validate OLM Bundle
          - check-skipped = Validate OLM Bundle
    merge_method: squash
    update_method: merge
    batch_size: 1

merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: queue approved pull requests
    conditions:
      - base = main
      - "#approved-reviews-by >= 1"
    actions:
      queue:
