package main

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
)

// This fixture is generated by Python build_plan, not the Go hash helpers.
func TestFrozenManifestIntegrity(t *testing.T) {
	original, err := os.ReadFile("testdata/frozen_manifest.json")
	if err != nil {
		t.Fatal(err)
	}
	var plan manifest
	if err = json.Unmarshal(original, &plan); err != nil {
		t.Fatal(err)
	}
	if err = validateFrozenManifest(original, plan); err != nil {
		t.Fatalf("Python-generated plan rejected: %v", err)
	}
	tests := []struct {
		name string
		edit func(map[string]interface{})
		want string
	}{
		{"sampling", func(p map[string]interface{}) {
			p["config"].(map[string]interface{})["models"].([]interface{})[0].(map[string]interface{})["sampling"].(map[string]interface{})["temperature"] = 0.8
		}, "config_sha256 mismatch"},
		{"updated config digest with stale identity", func(p map[string]interface{}) {
			config := p["config"].(map[string]interface{})
			config["id"] = "modified"
			updated, digestErr := manifestDigest(config)
			if digestErr != nil {
				t.Fatal(digestErr)
			}
			p["config_sha256"] = updated
		}, "experiment identity mismatch"},
		{"revision", func(p map[string]interface{}) { p["code_revision"] = "modified" }, "experiment identity mismatch"},
		{"planner", func(p map[string]interface{}) { p["planner_sha256"] = strings.Repeat("a", 64) }, "experiment identity mismatch"},
		{"identity", func(p map[string]interface{}) { p["experiment_id"] = strings.Repeat("a", 64) }, "experiment identity mismatch"},
		{"matrix id", func(p map[string]interface{}) {
			p["matrix"].([]interface{})[0].(map[string]interface{})["id"] = "changed"
		}, "plan matrix mismatch"},
		{"matrix items", func(p map[string]interface{}) {
			p["matrix"].([]interface{})[0].(map[string]interface{})["item_ids"] = []string{"changed"}
		}, "plan matrix mismatch"},
		{"matrix algorithm", func(p map[string]interface{}) {
			p["matrix"].([]interface{})[0].(map[string]interface{})["algorithm"] = "changed"
		}, "plan matrix mismatch"},
		{"missing cell", func(p map[string]interface{}) { p["matrix"] = p["matrix"].([]interface{})[1:] }, "plan matrix mismatch"},
		{"status", func(p map[string]interface{}) { p["status"] = "complete" }, "invalid plan schema or status"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			var saved map[string]interface{}
			decoder := json.NewDecoder(strings.NewReader(string(original)))
			decoder.UseNumber()
			if decodeErr := decoder.Decode(&saved); decodeErr != nil {
				t.Fatal(decodeErr)
			}
			test.edit(saved)
			data, marshalErr := json.Marshal(saved)
			if marshalErr != nil {
				t.Fatal(marshalErr)
			}
			var calls atomic.Int64
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				calls.Add(1)
				w.WriteHeader(http.StatusInternalServerError)
			}))
			defer server.Close()
			dir := t.TempDir()
			path := filepath.Join(dir, "manifest.json")
			if writeErr := os.WriteFile(path, data, 0o600); writeErr != nil {
				t.Fatal(writeErr)
			}
			output := filepath.Join(dir, "output")
			runErr := run(options{Manifest: path, Output: output, Endpoint: server.URL, TimeoutSeconds: 1})
			if runErr == nil || !strings.Contains(runErr.Error(), test.want) {
				t.Fatalf("got %v, want %s", runErr, test.want)
			}
			if calls.Load() != 0 {
				t.Fatal("invalid plan dispatched provider calls")
			}
			if _, statErr := os.Stat(output); !os.IsNotExist(statErr) {
				t.Fatalf("invalid plan created output: %v", statErr)
			}
		})
	}
}

func TestManifestCanonicalJSON(t *testing.T) {
	for input, expected := range map[string]string{
		`{"x":1.0,"y":1e-7,"z":1e+16}`:     "c4cb72d15adefc72d6cfd0f9e3c36a08e6204911f08d377200a8061429ee1b8c",
		`{"x":"中文<&>\u2028\u2029\\u2028"}`: "f18c95d169d9d898210a533a8cab5e403634d77909b8d4a7b6a5aae7e23b4540",
	} {
		decoder := json.NewDecoder(strings.NewReader(input))
		decoder.UseNumber()
		value, err := readManifestValue(decoder)
		if err != nil {
			t.Fatal(err)
		}
		actual, digestErr := manifestDigest(value)
		if digestErr != nil || actual != expected {
			t.Fatalf("digest = %s, %v; want %s", actual, digestErr, expected)
		}
	}
	decoder := json.NewDecoder(strings.NewReader(`{"x":1,"x":2}`))
	if _, err := readManifestValue(decoder); err == nil {
		t.Fatal("duplicate key accepted")
	}
}
