# Grafana datasource configuration for Jaeger/Tempo tracing
# Provisioned automatically when Grafana starts

apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
