apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: vllm-semantic-router-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: semantic-router-stack
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin
