package evaluationplane

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"sync"
	"time"
)

const (
	controlledPairProtocolVersion = "evaluation-controlled-pair.v1"
	controlledPairInterleaveABBA  = "abba-interleaved.v1"
)

const (
	controlledPairRoleBaseline  = "baseline"
	controlledPairRoleCandidate = "candidate"
)

// controlledPairLoadContext is generated by the server broker. It makes the
// load state of every observation explicit instead of asking a report reducer
// to infer it after two independent runs have completed.
type controlledPairLoadContext struct {
	Concurrency  int64  `json:"concurrency"`
	Phase        string `json:"phase"`
	Repetition   *int64 `json:"repetition,omitempty"`
	RequestIndex *int64 `json:"request_index,omitempty"`
}

// controlledPairObservation proves that an upstream request was admitted by
// one server-owned interleaving coordinator. The receipt for the broker entry
// covers this object, so a worker cannot add or rewrite pairing provenance.
type controlledPairObservation struct {
	ContractVersion       string                    `json:"contract_version"`
	SessionID             string                    `json:"session_id"`
	Protocol              string                    `json:"protocol"`
	Role                  string                    `json:"role"`
	Cohort                string                    `json:"cohort"`
	VariantManifestDigest string                    `json:"variant_manifest_digest"`
	CoordinateDigest      string                    `json:"coordinate_digest"`
	BlockID               string                    `json:"block_id"`
	Order                 string                    `json:"order"`
	Position              int                       `json:"position"`
	AttemptID             string                    `json:"attempt_id"`
	ObservedAt            time.Time                 `json:"observed_at"`
	CompletedAt           time.Time                 `json:"completed_at"`
	Load                  controlledPairLoadContext `json:"load"`
}

type controlledPairRunContext struct {
	role        string
	coordinator *controlledPairCoordinator
	credentials workerBrokerCredentials
}

type controlledPairCoordinate struct {
	trackID   TrackID
	caseID    string
	attemptID string
	operation string
	armID     string
}

func (coordinate controlledPairCoordinate) canonical() string {
	return string(coordinate.trackID) + "\x00" + coordinate.caseID + "\x00" +
		coordinate.attemptID + "\x00" + coordinate.operation + "\x00" + coordinate.armID
}

type controlledPairWaiter struct {
	role        string
	ready       chan struct{}
	observation *controlledPairObservation
}

type controlledPairBlock struct {
	waiters map[string]*controlledPairWaiter
}

type controlledPairCoordinator struct {
	sessionID  string
	seed       int64
	manifests  map[string]RunManifest
	sharedArms map[string]bool

	mu        sync.Mutex
	blocks    map[controlledPairCoordinate]*controlledPairBlock
	abortErr  error
	done      chan struct{}
	abortOnce sync.Once
}

type controlledPairLease struct {
	coordinator *controlledPairCoordinator
	coordinate  controlledPairCoordinate
	role        string
	position    int
	once        sync.Once
}

var capacityAttemptPattern = regexp.MustCompile(`^capacity-c([1-9][0-9]*)-([wm])([0-9]+)-q([0-9]+)$`)

func newControlledPairCoordinator(
	sessionID string,
	seed int64,
	baseline RunManifest,
	candidate RunManifest,
) *controlledPairCoordinator {
	sharedArms := make(map[string]bool)
	baselineArms := manifestArmIDs(baseline.Target.Mixture)
	for armID := range manifestArmIDs(candidate.Target.Mixture) {
		if baselineArms[armID] {
			sharedArms[armID] = true
		}
	}
	return &controlledPairCoordinator{
		sessionID: sessionID,
		seed:      seed,
		manifests: map[string]RunManifest{
			controlledPairRoleBaseline:  baseline,
			controlledPairRoleCandidate: candidate,
		},
		sharedArms: sharedArms,
		blocks:     make(map[controlledPairCoordinate]*controlledPairBlock),
		done:       make(chan struct{}),
	}
}

func manifestArmIDs(mixture *ManifestMixture) map[string]bool {
	result := make(map[string]bool)
	if mixture == nil {
		return result
	}
	for _, arm := range mixture.ModelArms {
		result[arm.ID] = true
	}
	return result
}

func (coordinator *controlledPairCoordinator) before(
	ctx context.Context,
	role string,
	request workerBrokerRequest,
	payload []byte,
) (*controlledPairObservation, *controlledPairLease, error) {
	if request.Operation == workerBrokerListModels {
		return nil, nil, nil
	}
	manifest, validRole := coordinator.manifests[role]
	if !validRole {
		return nil, nil, fmt.Errorf("controlled pair role is invalid")
	}
	coordinate, cohort, err := coordinator.coordinate(role, request, payload)
	if err != nil {
		return nil, nil, err
	}
	load, err := controlledPairRequestLoad(manifest, request)
	if err != nil {
		return nil, nil, err
	}
	coordinateDigest := digestString("controlled-pair-coordinate:" + coordinate.canonical())
	if cohort != campaignArmCohortPaired {
		return coordinator.unpairedObservation(
			role, cohort, manifest, coordinate, coordinateDigest, request.AttemptID, load,
		), nil, nil
	}

	waiter := &controlledPairWaiter{role: role, ready: make(chan struct{})}
	coordinator.mu.Lock()
	if coordinator.abortErr != nil {
		err := coordinator.abortErr
		coordinator.mu.Unlock()
		return nil, nil, err
	}
	block := coordinator.blocks[coordinate]
	if block == nil {
		block = &controlledPairBlock{waiters: make(map[string]*controlledPairWaiter, 2)}
		coordinator.blocks[coordinate] = block
	}
	if block.waiters[role] != nil {
		coordinator.mu.Unlock()
		return nil, nil, fmt.Errorf("controlled pair duplicates one observation coordinate")
	}
	block.waiters[role] = waiter
	if len(block.waiters) == 2 {
		order := coordinator.orderFor(coordinate)
		firstRole, secondRole := controlledPairRoleBaseline, controlledPairRoleCandidate
		if order == "BA" {
			firstRole, secondRole = secondRole, firstRole
		}
		blockID := digestString("controlled-pair-block:" + coordinator.sessionID + ":" + coordinate.canonical())
		for _, assignment := range []struct {
			role     string
			position int
		}{{firstRole, 1}, {secondRole, 2}} {
			variant := coordinator.manifests[assignment.role]
			block.waiters[assignment.role].observation = &controlledPairObservation{
				ContractVersion: controlledPairProtocolVersion,
				SessionID:       coordinator.sessionID, Protocol: controlledPairInterleaveABBA,
				Role: assignment.role, Cohort: campaignArmCohortPaired,
				VariantManifestDigest: variant.ManifestDigest,
				CoordinateDigest:      coordinateDigest, BlockID: blockID,
				Order: order, Position: assignment.position,
				AttemptID: request.AttemptID,
				Load: func() controlledPairLoadContext {
					if assignment.role == role {
						return load
					}
					otherLoad, _ := controlledPairRequestLoad(variant, request)
					return otherLoad
				}(),
			}
		}
		close(block.waiters[firstRole].ready)
	}
	coordinator.mu.Unlock()

	select {
	case <-waiter.ready:
		waiter.observation.ObservedAt = time.Now().UTC()
		return waiter.observation, &controlledPairLease{
			coordinator: coordinator, coordinate: coordinate, role: role,
			position: waiter.observation.Position,
		}, nil
	case <-coordinator.done:
		coordinator.mu.Lock()
		err := coordinator.abortErr
		coordinator.mu.Unlock()
		if err == nil {
			err = fmt.Errorf("controlled pair execution stopped")
		}
		return nil, nil, err
	case <-ctx.Done():
		return nil, nil, ctx.Err()
	}
}

func (coordinator *controlledPairCoordinator) unpairedObservation(
	role, cohort string,
	manifest RunManifest,
	coordinate controlledPairCoordinate,
	coordinateDigest, attemptID string,
	load controlledPairLoadContext,
) *controlledPairObservation {
	order := "A"
	if role == controlledPairRoleCandidate {
		order = "B"
	}
	return &controlledPairObservation{
		ContractVersion: controlledPairProtocolVersion,
		SessionID:       coordinator.sessionID, Protocol: controlledPairInterleaveABBA,
		Role: role, Cohort: cohort, VariantManifestDigest: manifest.ManifestDigest,
		CoordinateDigest: coordinateDigest,
		BlockID: digestString(
			"controlled-pair-unpaired:" + coordinator.sessionID + ":" + role + ":" + coordinate.canonical(),
		),
		Order: order, Position: 1, AttemptID: attemptID, Load: load,
	}
}

func (coordinator *controlledPairCoordinator) coordinate(
	role string,
	request workerBrokerRequest,
	payload []byte,
) (controlledPairCoordinate, string, error) {
	coordinate := controlledPairCoordinate{
		trackID: request.TrackID, caseID: request.CaseID,
		attemptID: request.AttemptID, operation: request.Operation,
	}
	if request.Operation != workerBrokerArmChatCompletion {
		return coordinate, campaignArmCohortPaired, nil
	}
	manifest := coordinator.manifests[role]
	requested := brokerRequestedModel(request.Operation, payload)
	if requested == nil {
		return controlledPairCoordinate{}, "", fmt.Errorf("controlled model-pool request omits its frozen arm")
	}
	armID := manifestArmIDForModel(manifest.Target.Mixture, *requested)
	if armID == "" {
		return controlledPairCoordinate{}, "", fmt.Errorf("controlled model-pool request does not identify a frozen arm")
	}
	coordinate.armID = armID
	if coordinator.sharedArms[armID] {
		return coordinate, campaignArmCohortPaired, nil
	}
	if role == controlledPairRoleBaseline {
		return coordinate, campaignArmCohortBaselineOnly, nil
	}
	return coordinate, campaignArmCohortCandidateOnly, nil
}

func manifestArmIDForModel(mixture *ManifestMixture, model string) string {
	if mixture == nil {
		return ""
	}
	for _, arm := range mixture.ModelArms {
		if model == arm.ID || model == arm.Model {
			return arm.ID
		}
	}
	return ""
}

func controlledPairRequestLoad(manifest RunManifest, request workerBrokerRequest) (controlledPairLoadContext, error) {
	load := controlledPairLoadContext{Concurrency: int64(manifest.Concurrency), Phase: "single"}
	if request.TrackID != "capacity" {
		return load, nil
	}
	matches := capacityAttemptPattern.FindStringSubmatch(request.AttemptID)
	if len(matches) != 5 {
		return controlledPairLoadContext{}, fmt.Errorf("controlled capacity attempt has no exact load context")
	}
	concurrency, firstErr := strconv.ParseInt(matches[1], 10, 64)
	repetition, secondErr := strconv.ParseInt(matches[3], 10, 64)
	requestIndex, thirdErr := strconv.ParseInt(matches[4], 10, 64)
	if firstErr != nil || secondErr != nil || thirdErr != nil || concurrency < 1 ||
		repetition < 0 || requestIndex < 0 {
		return controlledPairLoadContext{}, fmt.Errorf("controlled capacity load context is invalid")
	}
	phase := "warmup"
	if matches[2] == "m" {
		phase = "measurement"
	}
	load.Concurrency = concurrency
	load.Phase = phase
	load.Repetition = &repetition
	load.RequestIndex = &requestIndex
	return load, nil
}

func (coordinator *controlledPairCoordinator) orderFor(coordinate controlledPairCoordinate) string {
	value := digestString(strconv.FormatInt(coordinator.seed, 10) + ":" + coordinate.canonical())
	// The final hexadecimal nibble is uniformly derived from the frozen seed and
	// coordinate. Alternating AB/BA removes a systematic first-position bias.
	last := value[len(value)-1]
	if (last >= '0' && last <= '9' && (last-'0')%2 == 0) ||
		(last >= 'a' && last <= 'f' && (last-'a')%2 == 0) {
		return "AB"
	}
	return "BA"
}

func (lease *controlledPairLease) complete(completedAt time.Time) {
	if lease == nil {
		return
	}
	lease.once.Do(func() {
		coordinator := lease.coordinator
		coordinator.mu.Lock()
		defer coordinator.mu.Unlock()
		block := coordinator.blocks[lease.coordinate]
		if block == nil {
			return
		}
		waiter := block.waiters[lease.role]
		if waiter != nil && waiter.observation != nil {
			waiter.observation.CompletedAt = completedAt.UTC()
		}
		if lease.position == 1 {
			otherRole := controlledPairRoleBaseline
			if lease.role == controlledPairRoleBaseline {
				otherRole = controlledPairRoleCandidate
			}
			if other := block.waiters[otherRole]; other != nil {
				close(other.ready)
			}
			return
		}
		delete(coordinator.blocks, lease.coordinate)
	})
}

func (coordinator *controlledPairCoordinator) abort(err error) {
	if err == nil {
		return
	}
	coordinator.abortOnce.Do(func() {
		coordinator.mu.Lock()
		coordinator.abortErr = fmt.Errorf("controlled pair peer failed: %w", err)
		coordinator.mu.Unlock()
		close(coordinator.done)
	})
}
