package evaluationplane

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
)

const (
	MetricAnalysisCatalogSchemaVersion = "metric-analysis-catalog.v1"
	MetricAnalysisContractVersion      = "metric-analysis.v1"
)

var (
	ErrUnknownMetricAnalysisID   = errors.New("unknown evaluation metric id")
	ErrAmbiguousMetricAnalysisID = errors.New("ambiguous evaluation metric id")
)

// The canonical asset is Python wheel package data. This embedded copy and the
// TypeScript bundle are generated by tools/ci/sync_evaluation_catalogs.py and
// byte-for-byte gated in metric_analysis_catalog_test.go.
//
//go:embed metric_analysis_catalog.v1.json
var metricAnalysisCatalogJSON []byte

type MetricAnalysisPlannedUnitFilter struct {
	Field   string `json:"field"`
	Capture string `json:"capture"`
}

type MetricAnalysisPlannedUnitProjection struct {
	Source             string                            `json:"source"`
	TrackID            TrackID                           `json:"track_id"`
	Coordinates        []string                          `json:"coordinates"`
	RequiredDimensions []string                          `json:"required_dimensions,omitempty"`
	Filters            []MetricAnalysisPlannedUnitFilter `json:"filters,omitempty"`
}

// MetricAnalysisCatalogSpecification is the resolved immutable contract for a
// concrete metric ID. AnalysisRef is catalog identity, not a report field.
type MetricAnalysisCatalogSpecification struct {
	AnalysisRef           string                              `json:"id"`
	TrackID               TrackID                             `json:"track_id"`
	EstimatorID           string                              `json:"estimator_id"`
	EstimatorVersion      string                              `json:"estimator_version"`
	AnalysisUnit          string                              `json:"analysis_unit"`
	ClusterUnit           string                              `json:"cluster_unit"`
	Weighting             string                              `json:"weighting"`
	Missingness           string                              `json:"missingness"`
	ExclusionPolicy       string                              `json:"exclusion_policy"`
	PlannedUnitProjection MetricAnalysisPlannedUnitProjection `json:"planned_unit_projection"`
}

type MetricAnalysisCatalogMatch struct {
	MetricID      string
	FamilyID      string
	Captures      map[string]string
	Specification MetricAnalysisCatalogSpecification
}

type metricAnalysisStaticEntry struct {
	ID          string `json:"id"`
	AnalysisRef string `json:"analysis_ref"`
}

type metricAnalysisCapture struct {
	Name    string   `json:"name"`
	Group   int      `json:"group"`
	Type    string   `json:"type"`
	Values  []string `json:"values,omitempty"`
	Minimum *int     `json:"minimum,omitempty"`
	Maximum *int     `json:"maximum,omitempty"`
}

type metricAnalysisVariant struct {
	Value       string `json:"value"`
	AnalysisRef string `json:"analysis_ref"`
}

type metricAnalysisExample struct {
	MetricID    string            `json:"metric_id"`
	Captures    map[string]string `json:"captures"`
	AnalysisRef string            `json:"analysis_ref"`
}

type metricAnalysisDynamicFamily struct {
	ID              string                  `json:"id"`
	LiteralPrefix   string                  `json:"literal_prefix"`
	Pattern         string                  `json:"pattern"`
	Captures        []metricAnalysisCapture `json:"captures"`
	SelectorCapture string                  `json:"selector_capture"`
	Variants        []metricAnalysisVariant `json:"variants"`
	Examples        []metricAnalysisExample `json:"examples"`
	compiled        *regexp.Regexp
}

type metricAnalysisEncodingVector struct {
	Raw     string `json:"raw"`
	Encoded string `json:"encoded"`
}

type metricAnalysisIdentifierEncoding struct {
	Scheme         string                         `json:"scheme"`
	RawPattern     string                         `json:"raw_pattern"`
	DirectPattern  string                         `json:"direct_pattern"`
	ReservedPrefix string                         `json:"reserved_prefix"`
	EncodedPattern string                         `json:"encoded_pattern"`
	Vectors        []metricAnalysisEncodingVector `json:"vectors"`
	raw            *regexp.Regexp
	direct         *regexp.Regexp
	encoded        *regexp.Regexp
}

type metricAnalysisCatalogDocument struct {
	SchemaVersion             string                               `json:"schema_version"`
	ProvenanceContractVersion string                               `json:"provenance_contract_version"`
	IdentifierEncoding        metricAnalysisIdentifierEncoding     `json:"identifier_encoding"`
	AnalysisTemplates         []MetricAnalysisCatalogSpecification `json:"analysis_templates"`
	StaticMetrics             []metricAnalysisStaticEntry          `json:"static_metrics"`
	DynamicFamilies           []metricAnalysisDynamicFamily        `json:"dynamic_families"`
}

type metricAnalysisCatalogIndex struct {
	document  metricAnalysisCatalogDocument
	templates map[string]MetricAnalysisCatalogSpecification
	static    map[string]metricAnalysisStaticEntry
}

var (
	metricAnalysisCatalogOnce sync.Once
	metricAnalysisCatalogData metricAnalysisCatalogIndex
	metricAnalysisCatalogErr  error
)

func loadMetricAnalysisCatalog() {
	metricAnalysisCatalogData, metricAnalysisCatalogErr = decodeMetricAnalysisCatalog(metricAnalysisCatalogJSON)
}

func ValidateMetricAnalysisCatalog() error {
	metricAnalysisCatalogOnce.Do(loadMetricAnalysisCatalog)
	return metricAnalysisCatalogErr
}

func decodeMetricAnalysisCatalog(data []byte) (metricAnalysisCatalogIndex, error) {
	if err := rejectDuplicateJSONKeys(data); err != nil {
		return metricAnalysisCatalogIndex{}, fmt.Errorf("validate metric analysis catalog JSON: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var document metricAnalysisCatalogDocument
	if err := decoder.Decode(&document); err != nil {
		return metricAnalysisCatalogIndex{}, fmt.Errorf("decode metric analysis catalog: %w", err)
	}
	if err := metricAnalysisCatalogEOF(decoder); err != nil {
		return metricAnalysisCatalogIndex{}, err
	}
	index := metricAnalysisCatalogIndex{document: document}
	if err := validateMetricAnalysisCatalogDocument(&index); err != nil {
		return metricAnalysisCatalogIndex{}, err
	}
	return index, nil
}

func metricAnalysisCatalogEOF(decoder *json.Decoder) error {
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return fmt.Errorf("metric analysis catalog contains trailing JSON")
		}
		return fmt.Errorf("decode metric analysis catalog trailing data: %w", err)
	}
	return nil
}

func validateMetricAnalysisCatalogDocument(index *metricAnalysisCatalogIndex) error {
	document := &index.document
	if document.SchemaVersion != MetricAnalysisCatalogSchemaVersion || document.ProvenanceContractVersion != MetricAnalysisContractVersion {
		return fmt.Errorf("metric analysis catalog version is invalid")
	}
	if err := validateMetricAnalysisEncoding(&document.IdentifierEncoding); err != nil {
		return err
	}
	if err := validateMetricAnalysisTemplates(index); err != nil {
		return err
	}
	if err := validateMetricAnalysisDynamicFamilies(index); err != nil {
		return err
	}
	if err := validateMetricAnalysisStaticMetrics(index); err != nil {
		return err
	}
	if err := validateMetricAnalysisTemplateReferences(index); err != nil {
		return err
	}
	return validateMetricAnalysisFamilyExamples(index)
}

func validateMetricAnalysisTemplates(index *metricAnalysisCatalogIndex) error {
	document := &index.document
	if len(document.AnalysisTemplates) == 0 {
		return fmt.Errorf("metric analysis catalog templates are missing")
	}
	index.templates = make(map[string]MetricAnalysisCatalogSpecification, len(document.AnalysisTemplates))
	templateIDs := make([]string, 0, len(document.AnalysisTemplates))
	for _, specification := range document.AnalysisTemplates {
		if err := validateMetricAnalysisTemplate(specification, nil); err != nil {
			return err
		}
		if _, duplicate := index.templates[specification.AnalysisRef]; duplicate {
			return fmt.Errorf("metric analysis template %q is duplicated", specification.AnalysisRef)
		}
		index.templates[specification.AnalysisRef] = specification
		templateIDs = append(templateIDs, specification.AnalysisRef)
	}
	if !sort.StringsAreSorted(templateIDs) {
		return fmt.Errorf("metric analysis templates are not sorted")
	}
	return nil
}

func validateMetricAnalysisDynamicFamilies(index *metricAnalysisCatalogIndex) error {
	document := &index.document
	if len(document.DynamicFamilies) == 0 {
		return fmt.Errorf("metric analysis catalog dynamic families are missing")
	}
	prefixes := make([]string, 0, len(document.DynamicFamilies))
	familyIDs := make([]string, 0, len(document.DynamicFamilies))
	for familyIndex := range document.DynamicFamilies {
		family := &document.DynamicFamilies[familyIndex]
		if family.ID == "" || family.LiteralPrefix == "" || !strings.HasPrefix(family.Pattern, "^") || !strings.HasSuffix(family.Pattern, "$") {
			return fmt.Errorf("metric analysis dynamic family is invalid")
		}
		compiled, err := regexp.Compile(family.Pattern)
		if err != nil {
			return fmt.Errorf("compile metric analysis family %q: %w", family.ID, err)
		}
		family.compiled = compiled
		if len(family.Captures) != compiled.NumSubexp() || len(family.Captures) == 0 {
			return fmt.Errorf("metric analysis family %q capture cardinality is invalid", family.ID)
		}
		captureNames := make(map[string]struct{}, len(family.Captures))
		var selector metricAnalysisCapture
		for captureIndex, capture := range family.Captures {
			if capture.Group != captureIndex+1 || capture.Name == "" {
				return fmt.Errorf("metric analysis family %q capture is invalid", family.ID)
			}
			if _, duplicate := captureNames[capture.Name]; duplicate {
				return fmt.Errorf("metric analysis family %q capture is duplicated", family.ID)
			}
			captureNames[capture.Name] = struct{}{}
			switch capture.Type {
			case "encoded_portable_id":
				if len(capture.Values) != 0 || capture.Minimum != nil || capture.Maximum != nil {
					return fmt.Errorf("metric analysis encoded capture metadata is invalid")
				}
			case "enum":
				if !sortedDistinctStrings(capture.Values) || len(capture.Values) == 0 || capture.Minimum != nil || capture.Maximum != nil {
					return fmt.Errorf("metric analysis enum capture metadata is invalid")
				}
			case "positive_int":
				if capture.Minimum == nil || capture.Maximum == nil || *capture.Minimum < 1 || *capture.Maximum < *capture.Minimum || len(capture.Values) != 0 {
					return fmt.Errorf("metric analysis integer capture metadata is invalid")
				}
			default:
				return fmt.Errorf("metric analysis family %q capture type is invalid", family.ID)
			}
			if capture.Name == family.SelectorCapture {
				selector = capture
			}
		}
		if selector.Name == "" || len(family.Variants) == 0 || !sortedMetricAnalysisVariants(family.Variants) {
			return fmt.Errorf("metric analysis family %q variants are invalid", family.ID)
		}
		expectedVariants := []string{"*"}
		if selector.Type == "enum" {
			expectedVariants = selector.Values
		}
		actualVariants := make([]string, len(family.Variants))
		for variantIndex, variant := range family.Variants {
			actualVariants[variantIndex] = variant.Value
			specification, found := index.templates[variant.AnalysisRef]
			if !found {
				return fmt.Errorf("metric analysis family %q references unknown template %q", family.ID, variant.AnalysisRef)
			}
			if err := validateMetricAnalysisTemplate(specification, captureNames); err != nil {
				return err
			}
		}
		if !equalStrings(actualVariants, expectedVariants) {
			return fmt.Errorf("metric analysis family %q variants do not cover the selector", family.ID)
		}
		if len(family.Examples) == 0 {
			return fmt.Errorf("metric analysis family %q has no golden example", family.ID)
		}
		prefixes = append(prefixes, family.LiteralPrefix)
		familyIDs = append(familyIDs, family.ID)
	}
	if !sortedDistinctStrings(familyIDs) {
		return fmt.Errorf("metric analysis dynamic families are not sorted and unique")
	}
	for left := range prefixes {
		for right := left + 1; right < len(prefixes); right++ {
			if strings.HasPrefix(prefixes[left], prefixes[right]) || strings.HasPrefix(prefixes[right], prefixes[left]) {
				return fmt.Errorf("metric analysis dynamic family prefixes overlap")
			}
		}
	}
	return nil
}

func validateMetricAnalysisStaticMetrics(index *metricAnalysisCatalogIndex) error {
	document := &index.document
	if len(document.StaticMetrics) == 0 {
		return fmt.Errorf("metric analysis catalog static metrics are missing")
	}
	index.static = make(map[string]metricAnalysisStaticEntry, len(document.StaticMetrics))
	staticIDs := make([]string, 0, len(document.StaticMetrics))
	for _, entry := range document.StaticMetrics {
		if entry.ID == "" {
			return fmt.Errorf("metric analysis static id is blank")
		}
		if _, found := index.templates[entry.AnalysisRef]; !found {
			return fmt.Errorf("metric analysis static id %q references an unknown template", entry.ID)
		}
		if _, duplicate := index.static[entry.ID]; duplicate {
			return fmt.Errorf("metric analysis static id %q is duplicated", entry.ID)
		}
		for _, family := range document.DynamicFamilies {
			if family.compiled.MatchString(entry.ID) {
				return fmt.Errorf("metric analysis static id %q overlaps a dynamic family", entry.ID)
			}
		}
		index.static[entry.ID] = entry
		staticIDs = append(staticIDs, entry.ID)
	}
	if !sort.StringsAreSorted(staticIDs) {
		return fmt.Errorf("metric analysis static ids are not sorted")
	}
	return nil
}

func validateMetricAnalysisTemplateReferences(index *metricAnalysisCatalogIndex) error {
	referenced := make(map[string]struct{}, len(index.templates))
	for _, entry := range index.document.StaticMetrics {
		referenced[entry.AnalysisRef] = struct{}{}
	}
	for _, family := range index.document.DynamicFamilies {
		for _, variant := range family.Variants {
			referenced[variant.AnalysisRef] = struct{}{}
		}
	}
	if len(referenced) != len(index.templates) {
		return fmt.Errorf("metric analysis templates must be referenced exhaustively")
	}
	for templateID := range index.templates {
		if _, found := referenced[templateID]; !found {
			return fmt.Errorf("metric analysis templates must be referenced exhaustively")
		}
	}
	return nil
}

func validateMetricAnalysisFamilyExamples(index *metricAnalysisCatalogIndex) error {
	document := &index.document
	for _, family := range document.DynamicFamilies {
		for _, example := range family.Examples {
			match, err := resolveMetricAnalysisCatalog(index, example.MetricID)
			if err != nil || match.FamilyID != family.ID || match.Specification.AnalysisRef != example.AnalysisRef || !equalStringMaps(match.Captures, example.Captures) {
				return fmt.Errorf("metric analysis family %q golden example drifted", family.ID)
			}
		}
	}
	return nil
}

func validateMetricAnalysisEncoding(encoding *metricAnalysisIdentifierEncoding) error {
	if encoding.Scheme != "portable-segment-base64url.v1" || encoding.ReservedPrefix != "u-" || len(encoding.Vectors) == 0 {
		return fmt.Errorf("metric analysis identifier encoding is invalid")
	}
	var err error
	if encoding.raw, err = regexp.Compile(encoding.RawPattern); err != nil {
		return fmt.Errorf("compile raw metric subject pattern: %w", err)
	}
	if encoding.direct, err = regexp.Compile(encoding.DirectPattern); err != nil {
		return fmt.Errorf("compile direct metric subject pattern: %w", err)
	}
	if encoding.encoded, err = regexp.Compile(encoding.EncodedPattern); err != nil {
		return fmt.Errorf("compile encoded metric subject pattern: %w", err)
	}
	for _, vector := range encoding.Vectors {
		encoded, err := encodeMetricSubjectIDWith(vector.Raw, *encoding)
		if err != nil || encoded != vector.Encoded {
			return fmt.Errorf("metric analysis identifier encoding vector drifted")
		}
		decoded, err := decodeMetricSubjectIDWith(vector.Encoded, *encoding)
		if err != nil || decoded != vector.Raw {
			return fmt.Errorf("metric analysis identifier decoding vector drifted")
		}
	}
	return nil
}

func validateMetricAnalysisTemplate(specification MetricAnalysisCatalogSpecification, captures map[string]struct{}) error {
	if specification.AnalysisRef == "" || specification.TrackID == "" || specification.EstimatorID == "" || specification.EstimatorVersion == "" ||
		specification.AnalysisUnit == "" || specification.ClusterUnit == "" || specification.Weighting == "" ||
		specification.Missingness != "fail_closed" || specification.ExclusionPolicy != "exclude_unavailable_evidence" {
		return fmt.Errorf("metric analysis template %q is invalid", specification.AnalysisRef)
	}
	projection := specification.PlannedUnitProjection
	if projection.Source == "" || !containsTrack(allTrackIDs, projection.TrackID) || len(projection.Coordinates) == 0 ||
		!distinctNonBlankStrings(projection.Coordinates) || !distinctNonBlankStrings(projection.RequiredDimensions) {
		return fmt.Errorf("metric analysis template %q planned-unit projection is invalid", specification.AnalysisRef)
	}
	filterFields := make([]string, 0, len(projection.Filters))
	for _, filter := range projection.Filters {
		if filter.Field == "" || filter.Capture == "" || (captures != nil && !stringSetContains(captures, filter.Capture)) {
			return fmt.Errorf("metric analysis template %q planned-unit filter is invalid", specification.AnalysisRef)
		}
		filterFields = append(filterFields, filter.Field)
	}
	if !distinctNonBlankStrings(filterFields) {
		return fmt.Errorf("metric analysis template %q repeats a planned-unit filter", specification.AnalysisRef)
	}
	return nil
}

func ResolveMetricAnalysisCatalog(metricID string) (MetricAnalysisCatalogMatch, error) {
	metricAnalysisCatalogOnce.Do(loadMetricAnalysisCatalog)
	if metricAnalysisCatalogErr != nil {
		return MetricAnalysisCatalogMatch{}, metricAnalysisCatalogErr
	}
	return resolveMetricAnalysisCatalog(&metricAnalysisCatalogData, metricID)
}

func resolveMetricAnalysisCatalog(index *metricAnalysisCatalogIndex, metricID string) (MetricAnalysisCatalogMatch, error) {
	if metricID == "" || strings.TrimSpace(metricID) != metricID {
		return MetricAnalysisCatalogMatch{}, fmt.Errorf("%w: %q", ErrUnknownMetricAnalysisID, metricID)
	}
	if entry, found := index.static[metricID]; found {
		return MetricAnalysisCatalogMatch{
			MetricID: metricID, Captures: map[string]string{},
			Specification: copyMetricAnalysisCatalogSpecification(index.templates[entry.AnalysisRef]),
		}, nil
	}
	type candidate struct {
		family   metricAnalysisDynamicFamily
		captures map[string]string
	}
	candidates := make([]candidate, 0, 1)
	for _, family := range index.document.DynamicFamilies {
		parts := family.compiled.FindStringSubmatch(metricID)
		if parts == nil {
			continue
		}
		captures := make(map[string]string, len(family.Captures))
		valid := true
		for _, capture := range family.Captures {
			value := parts[capture.Group]
			if err := validateMetricAnalysisCapture(value, capture, index.document.IdentifierEncoding); err != nil {
				valid = false
				break
			}
			captures[capture.Name] = value
		}
		if valid {
			candidates = append(candidates, candidate{family: family, captures: captures})
		}
	}
	if len(candidates) == 0 {
		return MetricAnalysisCatalogMatch{}, fmt.Errorf("%w: %q", ErrUnknownMetricAnalysisID, metricID)
	}
	if len(candidates) != 1 {
		return MetricAnalysisCatalogMatch{}, fmt.Errorf("%w: %q", ErrAmbiguousMetricAnalysisID, metricID)
	}
	selected := candidates[0]
	selector := selected.captures[selected.family.SelectorCapture]
	analysisRef := ""
	for _, variant := range selected.family.Variants {
		if variant.Value == selector || variant.Value == "*" {
			analysisRef = variant.AnalysisRef
			if variant.Value == selector {
				break
			}
		}
	}
	if analysisRef == "" {
		return MetricAnalysisCatalogMatch{}, fmt.Errorf("%w: %q", ErrUnknownMetricAnalysisID, metricID)
	}
	return MetricAnalysisCatalogMatch{
		MetricID: metricID, FamilyID: selected.family.ID, Captures: copyStringMap(selected.captures),
		Specification: copyMetricAnalysisCatalogSpecification(index.templates[analysisRef]),
	}, nil
}

func validateMetricAnalysisCapture(value string, capture metricAnalysisCapture, encoding metricAnalysisIdentifierEncoding) error {
	switch capture.Type {
	case "encoded_portable_id":
		_, err := decodeMetricSubjectIDWith(value, encoding)
		return err
	case "positive_int":
		parsed, err := strconv.Atoi(value)
		if err != nil || strconv.Itoa(parsed) != value || capture.Minimum == nil || capture.Maximum == nil || parsed < *capture.Minimum || parsed > *capture.Maximum {
			return fmt.Errorf("metric analysis integer capture is invalid")
		}
		return nil
	case "enum":
		for _, allowed := range capture.Values {
			if value == allowed {
				return nil
			}
		}
		return fmt.Errorf("metric analysis enum capture is invalid")
	default:
		return fmt.Errorf("metric analysis capture type is invalid")
	}
}

func EncodeMetricAnalysisSubjectID(rawID string) (string, error) {
	metricAnalysisCatalogOnce.Do(loadMetricAnalysisCatalog)
	if metricAnalysisCatalogErr != nil {
		return "", metricAnalysisCatalogErr
	}
	return encodeMetricSubjectIDWith(rawID, metricAnalysisCatalogData.document.IdentifierEncoding)
}

func DecodeMetricAnalysisSubjectID(encodedID string) (string, error) {
	metricAnalysisCatalogOnce.Do(loadMetricAnalysisCatalog)
	if metricAnalysisCatalogErr != nil {
		return "", metricAnalysisCatalogErr
	}
	return decodeMetricSubjectIDWith(encodedID, metricAnalysisCatalogData.document.IdentifierEncoding)
}

func encodeMetricSubjectIDWith(rawID string, encoding metricAnalysisIdentifierEncoding) (string, error) {
	if encoding.raw == nil || !encoding.raw.MatchString(rawID) {
		return "", fmt.Errorf("metric subject id is not portable")
	}
	if !strings.HasPrefix(rawID, encoding.ReservedPrefix) && encoding.direct.MatchString(rawID) {
		return rawID, nil
	}
	encoded := encoding.ReservedPrefix + base64.RawURLEncoding.EncodeToString([]byte(rawID))
	if !encoding.encoded.MatchString(encoded) {
		return "", fmt.Errorf("metric subject id exceeds the encoded segment contract")
	}
	return encoded, nil
}

func decodeMetricSubjectIDWith(encodedID string, encoding metricAnalysisIdentifierEncoding) (string, error) {
	if !strings.HasPrefix(encodedID, encoding.ReservedPrefix) {
		if encoding.direct == nil || !encoding.direct.MatchString(encodedID) {
			return "", fmt.Errorf("metric subject segment is not canonical")
		}
		return encodedID, nil
	}
	if encoding.encoded == nil || !encoding.encoded.MatchString(encodedID) {
		return "", fmt.Errorf("metric subject segment is not canonical base64url")
	}
	decoded, err := base64.RawURLEncoding.DecodeString(strings.TrimPrefix(encodedID, encoding.ReservedPrefix))
	if err != nil {
		return "", fmt.Errorf("metric subject segment is not canonical base64url: %w", err)
	}
	rawID := string(decoded)
	canonical, err := encodeMetricSubjectIDWith(rawID, encoding)
	if err != nil || canonical != encodedID {
		return "", fmt.Errorf("metric subject segment has a non-canonical encoding")
	}
	return rawID, nil
}

func StaticMetricAnalysisIDsForTrack(trackID TrackID) []string {
	metricAnalysisCatalogOnce.Do(loadMetricAnalysisCatalog)
	if metricAnalysisCatalogErr != nil {
		return nil
	}
	result := make([]string, 0)
	for _, entry := range metricAnalysisCatalogData.document.StaticMetrics {
		if metricAnalysisCatalogData.templates[entry.AnalysisRef].TrackID == trackID {
			result = append(result, entry.ID)
		}
	}
	return result
}

func copyMetricAnalysisCatalogSpecification(value MetricAnalysisCatalogSpecification) MetricAnalysisCatalogSpecification {
	value.PlannedUnitProjection.Coordinates = append([]string(nil), value.PlannedUnitProjection.Coordinates...)
	value.PlannedUnitProjection.RequiredDimensions = append([]string(nil), value.PlannedUnitProjection.RequiredDimensions...)
	value.PlannedUnitProjection.Filters = append([]MetricAnalysisPlannedUnitFilter(nil), value.PlannedUnitProjection.Filters...)
	return value
}

func sortedDistinctStrings(values []string) bool {
	if !sort.StringsAreSorted(values) {
		return false
	}
	for index := 1; index < len(values); index++ {
		if values[index] == values[index-1] {
			return false
		}
	}
	return true
}

func distinctNonBlankStrings(values []string) bool {
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		if value == "" {
			return false
		}
		if _, duplicate := seen[value]; duplicate {
			return false
		}
		seen[value] = struct{}{}
	}
	return true
}

func sortedMetricAnalysisVariants(values []metricAnalysisVariant) bool {
	ids := make([]string, len(values))
	for index, value := range values {
		if value.Value == "" || value.AnalysisRef == "" {
			return false
		}
		ids[index] = value.Value
	}
	return sortedDistinctStrings(ids)
}

func equalStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func equalStringMaps(left, right map[string]string) bool {
	if len(left) != len(right) {
		return false
	}
	for key, value := range left {
		if right[key] != value {
			return false
		}
	}
	return true
}

func stringSetContains(values map[string]struct{}, value string) bool {
	_, found := values[value]
	return found
}
