apiVersion: v1
kind: Service
metadata:
  name: anthropic-backend
spec:
  type: ClusterIP
  selector:
    app: anthropic-backend
    app.kubernetes.io/name: anthropic-backend
  ports:
    - name: http
      port: 9080
      targetPort: shim
      protocol: TCP
