apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: valkey
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: default
spec:
  selector:
    app: valkey
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
    protocol: TCP
