# Prometheus configuration for semantic-router observability

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Semantic Router metrics
  - job_name: semantic-router
    metrics_path: /metrics
    static_configs:
      # Local: localhost:9190 / Compose: semantic-router:9190
      - targets: ["prometheus:9190"]
        labels:
          service: semantic-router
          environment: docker

  # Optional: Envoy proxy metrics
  # Uncomment if Envoy is running
  # - job_name: envoy
  #   metrics_path: /stats/prometheus
  #   static_configs:
  #     - targets: ["${ENVOY_TARGET:-envoy-proxy:19000}"]
  #       labels:
  #         service: envoy
  #         environment: docker
