version: '3.8'

services:
  # Jaeger all-in-one for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - router-network

  # Semantic Router with tracing enabled
  semantic-router:
    image: vllm-semantic-router:latest
    container_name: semantic-router
    depends_on:
      - jaeger
    ports:
      - "50051:50051" # gRPC ExtProc
      - "8080:8080"   # Classification API
      - "9190:9190"   # Metrics
    volumes:
      - ./config:/config
    environment:
      - CONFIG_PATH=/config/config.tracing.yaml
    networks:
      - router-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      - router-network

networks:
  router-network:
    driver: bridge

volumes:
  grafana-storage:
