apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  labels:
    app: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - name: chat-ui
          image: ghcr.io/huggingface/chat-ui-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: OPENAI_BASE_URL
              value: "http://envoy-proxy.vllm-semantic-router-system.svc.cluster.local:8801/v1"
            - name: OPENAI_API_KEY
              value: "changeme"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017"
            - name: MONGODB_DB_NAME
              value: "chat-ui"
            - name: PUBLIC_APP_NAME
              value: "HuggingChat"
            - name: PUBLIC_APP_ASSETS
              value: "chatui"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  labels:
    app: chat-ui
spec:
  selector:
    app: chat-ui
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
