/* eslint-disable */
// This file is generated by `npm run committers:activity`.
// Activity includes authored PRs, submitted reviews, authored issues, and sustained issue-comment participation.

export type CommitterActivityStatus = 'active' | 'emeritus'

export interface CommitterActivityEntry {
  name: string
  login: string
  pullRequests: number
  reviews: number
  issues: number
  total: number
  status: CommitterActivityStatus
}

export const committerActivityWindow = {
  "generatedAt": "2026-08-26",
  "cutoffDate": "2026-05-26",
  "months": 3,
  "minimumCommentedIssueThreads": 2,
  "activeCount": 11,
  "emeritusCount": 20
}

export const committerActivityEntries: CommitterActivityEntry[] = [
  {
    "name": "FAUST",
    "login": "FAUST-BENCHOU",
    "pullRequests": 20,
    "reviews": 87,
    "issues": 28,
    "total": 135,
    "status": "active"
  },
  {
    "name": "David Shrader",
    "login": "shraderdm",
    "pullRequests": 17,
    "reviews": 6,
    "issues": 16,
    "total": 39,
    "status": "active"
  },
  {
    "name": "yangw",
    "login": "drivebyer",
    "pullRequests": 23,
    "reviews": 52,
    "issues": 18,
    "total": 93,
    "status": "active"
  },
  {
    "name": "Ramakrishnan Sathyavageeswaran",
    "login": "ramkrishs",
    "pullRequests": 2,
    "reviews": 4,
    "issues": 0,
    "total": 6,
    "status": "active"
  },
  {
    "name": "Teemu Kuusisto",
    "login": "siloteemu",
    "pullRequests": 6,
    "reviews": 1,
    "issues": 5,
    "total": 12,
    "status": "active"
  },
  {
    "name": "Akshay Viswanathan",
    "login": "akshayv",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 2,
    "total": 3,
    "status": "active"
  },
  {
    "name": "Theo Hsiung",
    "login": "theohsiung",
    "pullRequests": 55,
    "reviews": 14,
    "issues": 77,
    "total": 146,
    "status": "active"
  },
  {
    "name": "Wilson Wu",
    "login": "wilsonwu",
    "pullRequests": 43,
    "reviews": 13,
    "issues": 29,
    "total": 85,
    "status": "active"
  },
  {
    "name": "Yincheng Ren",
    "login": "Peterren",
    "pullRequests": 22,
    "reviews": 5,
    "issues": 14,
    "total": 41,
    "status": "active"
  },
  {
    "name": "Chen Wang",
    "login": "wangchen615",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yue Zhu",
    "login": "yuezhu1",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Senan Zedan",
    "login": "szedan-rh",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yossi Ovadia",
    "login": "yossiovadia",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "samzong",
    "login": "samzong",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Liav Weiss",
    "login": "liavweiss",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Asaad Balum",
    "login": "asaadbalum",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yehudit",
    "login": "yehuditkerido",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Noa Limoy",
    "login": "noalimoy",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Marina Koushnir",
    "login": "mkoushni",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "JaredforReal",
    "login": "JaredforReal",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Abdallah Samara",
    "login": "abdallahsamabd",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Hen Schwartz",
    "login": "henschwartz",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Srinivas A",
    "login": "srini-abhiram",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "carlory",
    "login": "carlory",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Jintao Zhang",
    "login": "tao12345666333",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "yuluo-yx",
    "login": "yuluo-yx",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "cryo-zd",
    "login": "cryo-zd",
    "pullRequests": 4,
    "reviews": 2,
    "issues": 1,
    "total": 7,
    "status": "active"
  },
  {
    "name": "OneZero-Y",
    "login": "OneZero-Y",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "aeft",
    "login": "aeft",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Hao Wu",
    "login": "haowu1234",
    "pullRequests": 15,
    "reviews": 14,
    "issues": 12,
    "total": 41,
    "status": "active"
  },
  {
    "name": "Qiping Pan",
    "login": "ppppqp",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  }
]
