/* eslint-disable */
// This file is generated by `npm run committers:activity`.
// Activity includes authored PRs, submitted reviews, and authored or commented issues.

export type CommitterActivityStatus = 'active' | 'emeritus'

export interface CommitterActivityEntry {
  name: string
  login: string
  pullRequests: number
  reviews: number
  issues: number
  total: number
  status: CommitterActivityStatus
}

export const committerActivityWindow = {
  "generatedAt": "2026-07-14",
  "cutoffDate": "2026-04-14",
  "months": 3,
  "activeCount": 15,
  "emeritusCount": 14
}

export const committerActivityEntries: CommitterActivityEntry[] = [
  {
    "name": "FAUST",
    "login": "FAUST-BENCHOU",
    "pullRequests": 29,
    "reviews": 49,
    "issues": 27,
    "total": 105,
    "status": "active"
  },
  {
    "name": "David Shrader",
    "login": "shraderdm",
    "pullRequests": 27,
    "reviews": 7,
    "issues": 15,
    "total": 49,
    "status": "active"
  },
  {
    "name": "yangw",
    "login": "drivebyer",
    "pullRequests": 10,
    "reviews": 17,
    "issues": 7,
    "total": 34,
    "status": "active"
  },
  {
    "name": "Ramakrishnan Sathyavageeswaran",
    "login": "ramkrishs",
    "pullRequests": 6,
    "reviews": 0,
    "issues": 5,
    "total": 11,
    "status": "active"
  },
  {
    "name": "WUKUNTAI",
    "login": "WUKUNTAI-0211",
    "pullRequests": 41,
    "reviews": 19,
    "issues": 22,
    "total": 82,
    "status": "active"
  },
  {
    "name": "Aayush Saini",
    "login": "AayushSaini101",
    "pullRequests": 13,
    "reviews": 44,
    "issues": 38,
    "total": 95,
    "status": "active"
  },
  {
    "name": "siloteemu",
    "login": "siloteemu",
    "pullRequests": 11,
    "reviews": 1,
    "issues": 5,
    "total": 17,
    "status": "active"
  },
  {
    "name": "Chen Wang",
    "login": "wangchen615",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yue Zhu",
    "login": "yuezhu1",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Senan Zedan",
    "login": "szedan-rh",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yossi Ovadia",
    "login": "yossiovadia",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "samzong",
    "login": "samzong",
    "pullRequests": 0,
    "reviews": 1,
    "issues": 0,
    "total": 1,
    "status": "active"
  },
  {
    "name": "Liav Weiss",
    "login": "liavweiss",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Asaad Balum",
    "login": "asaadbalum",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 0,
    "total": 1,
    "status": "active"
  },
  {
    "name": "Yehudit",
    "login": "yehuditkerido",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Noa Limoy",
    "login": "noalimoy",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 1,
    "total": 2,
    "status": "active"
  },
  {
    "name": "Marina Koushnir",
    "login": "mkoushni",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "JaredforReal",
    "login": "JaredforReal",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Abdallah Samara",
    "login": "abdallahsamabd",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 0,
    "total": 1,
    "status": "active"
  },
  {
    "name": "Hen Schwartz",
    "login": "henschwartz",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 0,
    "total": 1,
    "status": "active"
  },
  {
    "name": "Srinivas A",
    "login": "srini-abhiram",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "carlory",
    "login": "carlory",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Jintao Zhang",
    "login": "tao12345666333",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "yuluo-yx",
    "login": "yuluo-yx",
    "pullRequests": 0,
    "reviews": 1,
    "issues": 0,
    "total": 1,
    "status": "active"
  },
  {
    "name": "cryo-zd",
    "login": "cryo-zd",
    "pullRequests": 9,
    "reviews": 4,
    "issues": 1,
    "total": 14,
    "status": "active"
  },
  {
    "name": "OneZero-Y",
    "login": "OneZero-Y",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "aeft",
    "login": "aeft",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Hao Wu",
    "login": "haowu1234",
    "pullRequests": 12,
    "reviews": 6,
    "issues": 12,
    "total": 30,
    "status": "active"
  },
  {
    "name": "Qiping Pan",
    "login": "ppppqp",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  }
]
