// Source SHA-256: 9b1824b090d7569f8d4140e94a5b3c10ad93f77204750722c806418a3fb96c3d
// Body SHA-256: 1b77d6448f5b6a75854eedcb73e17d11e018798b70a81ae8f8f23b0b5b42a1e9
/* eslint-disable */
// This file is generated by `npm run committers:activity`.
// Activity includes authored PRs, submitted reviews, authored issues, and sustained issue-comment participation.

export type CommitterActivityStatus = 'active' | 'emeritus'

export interface CommitterActivityEntry {
  name: string
  login: string
  pullRequests: number
  reviews: number
  issues: number
  total: number
  status: CommitterActivityStatus
}

export const committerActivityWindow = {
  "generatedAt": "2026-09-16",
  "cutoffDate": "2026-06-16",
  "months": 3,
  "minimumCommentedIssueThreads": 2,
  "activeCount": 10,
  "emeritusCount": 21
}

export const committerActivityEntries: CommitterActivityEntry[] = [
  {
    "name": "FAUST",
    "login": "FAUST-BENCHOU",
    "pullRequests": 14,
    "reviews": 298,
    "issues": 115,
    "total": 427,
    "status": "active"
  },
  {
    "name": "David Shrader",
    "login": "shraderdm",
    "pullRequests": 2,
    "reviews": 3,
    "issues": 9,
    "total": 14,
    "status": "active"
  },
  {
    "name": "yangw",
    "login": "drivebyer",
    "pullRequests": 33,
    "reviews": 66,
    "issues": 41,
    "total": 140,
    "status": "active"
  },
  {
    "name": "Ramakrishnan Sathyavageeswaran",
    "login": "ramkrishs",
    "pullRequests": 4,
    "reviews": 6,
    "issues": 11,
    "total": 21,
    "status": "active"
  },
  {
    "name": "Teemu Kuusisto",
    "login": "siloteemu",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Akshay Viswanathan",
    "login": "akshayv",
    "pullRequests": 1,
    "reviews": 0,
    "issues": 2,
    "total": 3,
    "status": "active"
  },
  {
    "name": "Theo Hsiung",
    "login": "theohsiung",
    "pullRequests": 35,
    "reviews": 22,
    "issues": 76,
    "total": 133,
    "status": "active"
  },
  {
    "name": "Wilson Wu",
    "login": "wilsonwu",
    "pullRequests": 36,
    "reviews": 179,
    "issues": 40,
    "total": 255,
    "status": "active"
  },
  {
    "name": "Yincheng Ren",
    "login": "Peterren",
    "pullRequests": 17,
    "reviews": 3,
    "issues": 10,
    "total": 30,
    "status": "active"
  },
  {
    "name": "Chen Wang",
    "login": "wangchen615",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yue Zhu",
    "login": "yuezhu1",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Senan Zedan",
    "login": "szedan-rh",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yossi Ovadia",
    "login": "yossiovadia",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "samzong",
    "login": "samzong",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Liav Weiss",
    "login": "liavweiss",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Asaad Balum",
    "login": "asaadbalum",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Yehudit",
    "login": "yehuditkerido",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Noa Limoy",
    "login": "noalimoy",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Marina Koushnir",
    "login": "mkoushni",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "JaredforReal",
    "login": "JaredforReal",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Abdallah Samara",
    "login": "abdallahsamabd",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Hen Schwartz",
    "login": "henschwartz",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Srinivas A",
    "login": "srini-abhiram",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "carlory",
    "login": "carlory",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Jintao Zhang",
    "login": "tao12345666333",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "yuluo-yx",
    "login": "yuluo-yx",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "cryo-zd",
    "login": "cryo-zd",
    "pullRequests": 0,
    "reviews": 1,
    "issues": 1,
    "total": 2,
    "status": "active"
  },
  {
    "name": "OneZero-Y",
    "login": "OneZero-Y",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "aeft",
    "login": "aeft",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  },
  {
    "name": "Hao Wu",
    "login": "haowu1234",
    "pullRequests": 15,
    "reviews": 13,
    "issues": 12,
    "total": 40,
    "status": "active"
  },
  {
    "name": "Qiping Pan",
    "login": "ppppqp",
    "pullRequests": 0,
    "reviews": 0,
    "issues": 0,
    "total": 0,
    "status": "emeritus"
  }
]
