/* eslint-disable */
// This file is generated by `npm run committers:stats`.
// Source: GitHub GraphQL pull requests + reviews; committers from teamMembers.tsx.

export type CommitterStatsRange = 'v03ToNow' | 'v02ToV03' | 'v01ToV02' | 'v0ToV01' | 'all'

export interface CommitterStatsEntry {
  rank: number
  key: string
  name: string
  login?: string
  avatarLogin?: string
  avatarUrl?: string
  avatarSeed: string
  reviews: number
  merges: number
  total: number
}

export interface CommitterStatsSnapshot {
  id: CommitterStatsRange
  label: string
  generatedAt: string
  startDate: string | null
  endDate: string
  description: string
  activeCommitters: number
  totalReviews: number
  totalMerges: number
  entries: CommitterStatsEntry[]
}

export const committerStatsGeneratedAt = '2026-07-13'

export const committerStatsData = {
  "v03ToNow": {
    "id": "v03ToNow",
    "label": "v0.3 -> Now",
    "generatedAt": "2026-07-13",
    "startDate": "2026-06-05",
    "endDate": "2026-07-13",
    "description": "Committer review and merge activity after v0.3.0.",
    "activeCommitters": 8,
    "totalReviews": 115,
    "totalMerges": 76,
    "entries": [
      {
        "rank": 1,
        "name": "Aayush Saini",
        "login": "AayushSaini101",
        "avatarLogin": "AayushSaini101",
        "avatarUrl": "https://github.com/AayushSaini101.png?size=160",
        "avatarSeed": "AayushSaini101",
        "key": "github:aayushsaini101",
        "reviews": 41,
        "merges": 31,
        "total": 72
      },
      {
        "rank": 2,
        "name": "FAUST",
        "login": "FAUST-BENCHOU",
        "avatarLogin": "FAUST-BENCHOU",
        "avatarUrl": "https://github.com/FAUST-BENCHOU.png?size=160",
        "avatarSeed": "FAUST-BENCHOU",
        "key": "github:faust-benchou",
        "reviews": 30,
        "merges": 11,
        "total": 41
      },
      {
        "rank": 3,
        "name": "WUKUNTAI",
        "login": "WUKUNTAI-0211",
        "avatarLogin": "WUKUNTAI-0211",
        "avatarUrl": "https://github.com/WUKUNTAI-0211.png?size=160",
        "avatarSeed": "WUKUNTAI-0211",
        "key": "github:wukuntai-0211",
        "reviews": 17,
        "merges": 19,
        "total": 36
      },
      {
        "rank": 4,
        "name": "yangw",
        "login": "drivebyer",
        "avatarLogin": "drivebyer",
        "avatarUrl": "https://github.com/drivebyer.png?size=160",
        "avatarSeed": "drivebyer",
        "key": "github:drivebyer",
        "reviews": 15,
        "merges": 13,
        "total": 28
      },
      {
        "rank": 5,
        "name": "Hao Wu",
        "login": "haowu1234",
        "avatarLogin": "haowu1234",
        "avatarUrl": "https://github.com/haowu1234.png?size=160",
        "avatarSeed": "haowu1234",
        "key": "github:haowu1234",
        "reviews": 4,
        "merges": 2,
        "total": 6
      },
      {
        "rank": 6,
        "name": "David Shrader",
        "login": "shraderdm",
        "avatarLogin": "shraderdm",
        "avatarUrl": "https://github.com/shraderdm.png?size=160",
        "avatarSeed": "shraderdm",
        "key": "github:shraderdm",
        "reviews": 5,
        "merges": 0,
        "total": 5
      },
      {
        "rank": 7,
        "name": "cryo-zd",
        "login": "cryo-zd",
        "avatarLogin": "cryo-zd",
        "avatarUrl": "https://github.com/cryo-zd.png?size=160",
        "avatarSeed": "cryo-zd",
        "key": "github:cryo-zd",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 8,
        "name": "siloteemu",
        "login": "siloteemu",
        "avatarLogin": "siloteemu",
        "avatarUrl": "https://github.com/siloteemu.png?size=160",
        "avatarSeed": "siloteemu",
        "key": "github:siloteemu",
        "reviews": 1,
        "merges": 0,
        "total": 1
      }
    ]
  },
  "v02ToV03": {
    "id": "v02ToV03",
    "label": "v0.2 -> v0.3",
    "generatedAt": "2026-07-13",
    "startDate": "2026-03-10",
    "endDate": "2026-06-05",
    "description": "Committer review and merge activity between v0.2.0 and v0.3.0.",
    "activeCommitters": 11,
    "totalReviews": 39,
    "totalMerges": 0,
    "entries": [
      {
        "rank": 1,
        "name": "Hao Wu",
        "login": "haowu1234",
        "avatarLogin": "haowu1234",
        "avatarUrl": "https://github.com/haowu1234.png?size=160",
        "avatarSeed": "haowu1234",
        "key": "github:haowu1234",
        "reviews": 18,
        "merges": 0,
        "total": 18
      },
      {
        "rank": 2,
        "name": "FAUST",
        "login": "FAUST-BENCHOU",
        "avatarLogin": "FAUST-BENCHOU",
        "avatarUrl": "https://github.com/FAUST-BENCHOU.png?size=160",
        "avatarSeed": "FAUST-BENCHOU",
        "key": "github:faust-benchou",
        "reviews": 7,
        "merges": 0,
        "total": 7
      },
      {
        "rank": 3,
        "name": "yuluo-yx",
        "login": "yuluo-yx",
        "avatarLogin": "yuluo-yx",
        "avatarUrl": "https://github.com/yuluo-yx.png?size=160",
        "avatarSeed": "yuluo-yx",
        "key": "github:yuluo-yx",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 4,
        "name": "cryo-zd",
        "login": "cryo-zd",
        "avatarLogin": "cryo-zd",
        "avatarUrl": "https://github.com/cryo-zd.png?size=160",
        "avatarSeed": "cryo-zd",
        "key": "github:cryo-zd",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 5,
        "name": "Senan Zedan",
        "login": "szedan-rh",
        "avatarLogin": "szedan-rh",
        "avatarUrl": "https://github.com/szedan-rh.png?size=160",
        "avatarSeed": "szedan-rh",
        "key": "github:szedan-rh",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 6,
        "name": "yangw",
        "login": "drivebyer",
        "avatarLogin": "drivebyer",
        "avatarUrl": "https://github.com/drivebyer.png?size=160",
        "avatarSeed": "drivebyer",
        "key": "github:drivebyer",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 7,
        "name": "Asaad Balum",
        "login": "asaadbalum",
        "avatarLogin": "asaadbalum",
        "avatarUrl": "https://github.com/asaadbalum.png?size=160",
        "avatarSeed": "asaadbalum",
        "key": "github:asaadbalum",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 8,
        "name": "David Shrader",
        "login": "shraderdm",
        "avatarLogin": "shraderdm",
        "avatarUrl": "https://github.com/shraderdm.png?size=160",
        "avatarSeed": "shraderdm",
        "key": "github:shraderdm",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 9,
        "name": "Liav Weiss",
        "login": "liavweiss",
        "avatarLogin": "liavweiss",
        "avatarUrl": "https://github.com/liavweiss.png?size=160",
        "avatarSeed": "liavweiss",
        "key": "github:liavweiss",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 10,
        "name": "samzong",
        "login": "samzong",
        "avatarLogin": "samzong",
        "avatarUrl": "https://github.com/samzong.png?size=160",
        "avatarSeed": "samzong",
        "key": "github:samzong",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 11,
        "name": "WUKUNTAI",
        "login": "WUKUNTAI-0211",
        "avatarLogin": "WUKUNTAI-0211",
        "avatarUrl": "https://github.com/WUKUNTAI-0211.png?size=160",
        "avatarSeed": "WUKUNTAI-0211",
        "key": "github:wukuntai-0211",
        "reviews": 1,
        "merges": 0,
        "total": 1
      }
    ]
  },
  "v01ToV02": {
    "id": "v01ToV02",
    "label": "v0.1 -> v0.2",
    "generatedAt": "2026-07-13",
    "startDate": "2026-01-05",
    "endDate": "2026-03-10",
    "description": "Committer review and merge activity between v0.1.0 and v0.2.0.",
    "activeCommitters": 9,
    "totalReviews": 62,
    "totalMerges": 14,
    "entries": [
      {
        "rank": 1,
        "name": "Hao Wu",
        "login": "haowu1234",
        "avatarLogin": "haowu1234",
        "avatarUrl": "https://github.com/haowu1234.png?size=160",
        "avatarSeed": "haowu1234",
        "key": "github:haowu1234",
        "reviews": 32,
        "merges": 5,
        "total": 37
      },
      {
        "rank": 2,
        "name": "samzong",
        "login": "samzong",
        "avatarLogin": "samzong",
        "avatarUrl": "https://github.com/samzong.png?size=160",
        "avatarSeed": "samzong",
        "key": "github:samzong",
        "reviews": 10,
        "merges": 7,
        "total": 17
      },
      {
        "rank": 3,
        "name": "Abdallah Samara",
        "login": "abdallahsamabd",
        "avatarLogin": "abdallahsamabd",
        "avatarUrl": "https://github.com/abdallahsamabd.png?size=160",
        "avatarSeed": "abdallahsamabd",
        "key": "github:abdallahsamabd",
        "reviews": 4,
        "merges": 1,
        "total": 5
      },
      {
        "rank": 4,
        "name": "Qiping Pan",
        "login": "ppppqp",
        "avatarLogin": "ppppqp",
        "avatarUrl": "https://github.com/ppppqp.png?size=160",
        "avatarSeed": "ppppqp",
        "key": "github:ppppqp",
        "reviews": 4,
        "merges": 0,
        "total": 4
      },
      {
        "rank": 5,
        "name": "Senan Zedan",
        "login": "szedan-rh",
        "avatarLogin": "szedan-rh",
        "avatarUrl": "https://github.com/szedan-rh.png?size=160",
        "avatarSeed": "szedan-rh",
        "key": "github:szedan-rh",
        "reviews": 3,
        "merges": 1,
        "total": 4
      },
      {
        "rank": 6,
        "name": "Yehudit",
        "login": "yehuditkerido",
        "avatarLogin": "yehuditkerido",
        "avatarUrl": "https://github.com/yehuditkerido.png?size=160",
        "avatarSeed": "yehuditkerido",
        "key": "github:yehuditkerido",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 7,
        "name": "yuluo-yx",
        "login": "yuluo-yx",
        "avatarLogin": "yuluo-yx",
        "avatarUrl": "https://github.com/yuluo-yx.png?size=160",
        "avatarSeed": "yuluo-yx",
        "key": "github:yuluo-yx",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 8,
        "name": "Liav Weiss",
        "login": "liavweiss",
        "avatarLogin": "liavweiss",
        "avatarUrl": "https://github.com/liavweiss.png?size=160",
        "avatarSeed": "liavweiss",
        "key": "github:liavweiss",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 9,
        "name": "Noa Limoy",
        "login": "noalimoy",
        "avatarLogin": "noalimoy",
        "avatarUrl": "https://github.com/noalimoy.png?size=160",
        "avatarSeed": "noalimoy",
        "key": "github:noalimoy",
        "reviews": 1,
        "merges": 0,
        "total": 1
      }
    ]
  },
  "v0ToV01": {
    "id": "v0ToV01",
    "label": "v0 -> v0.1",
    "generatedAt": "2026-07-13",
    "startDate": null,
    "endDate": "2026-01-05",
    "description": "Initial committer review and merge activity through v0.1.0.",
    "activeCommitters": 17,
    "totalReviews": 178,
    "totalMerges": 26,
    "entries": [
      {
        "rank": 1,
        "name": "JaredforReal",
        "login": "JaredforReal",
        "avatarLogin": "JaredforReal",
        "avatarUrl": "https://github.com/JaredforReal.png?size=160",
        "avatarSeed": "JaredforReal",
        "key": "github:jaredforreal",
        "reviews": 41,
        "merges": 13,
        "total": 54
      },
      {
        "rank": 2,
        "name": "yuluo-yx",
        "login": "yuluo-yx",
        "avatarLogin": "yuluo-yx",
        "avatarUrl": "https://github.com/yuluo-yx.png?size=160",
        "avatarSeed": "yuluo-yx",
        "key": "github:yuluo-yx",
        "reviews": 53,
        "merges": 0,
        "total": 53
      },
      {
        "rank": 3,
        "name": "samzong",
        "login": "samzong",
        "avatarLogin": "samzong",
        "avatarUrl": "https://github.com/samzong.png?size=160",
        "avatarSeed": "samzong",
        "key": "github:samzong",
        "reviews": 22,
        "merges": 7,
        "total": 29
      },
      {
        "rank": 4,
        "name": "Jintao Zhang",
        "login": "tao12345666333",
        "avatarLogin": "tao12345666333",
        "avatarUrl": "https://github.com/tao12345666333.png?size=160",
        "avatarSeed": "tao12345666333",
        "key": "github:tao12345666333",
        "reviews": 17,
        "merges": 0,
        "total": 17
      },
      {
        "rank": 5,
        "name": "Chen Wang",
        "login": "wangchen615",
        "avatarLogin": "wangchen615",
        "avatarUrl": "https://github.com/wangchen615.png?size=160",
        "avatarSeed": "wangchen615",
        "key": "github:wangchen615",
        "reviews": 10,
        "merges": 4,
        "total": 14
      },
      {
        "rank": 6,
        "name": "OneZero-Y",
        "login": "OneZero-Y",
        "avatarLogin": "OneZero-Y",
        "avatarUrl": "https://github.com/OneZero-Y.png?size=160",
        "avatarSeed": "OneZero-Y",
        "key": "github:onezero-y",
        "reviews": 8,
        "merges": 0,
        "total": 8
      },
      {
        "rank": 7,
        "name": "Yue Zhu",
        "login": "yuezhu1",
        "avatarLogin": "yuezhu1",
        "avatarUrl": "https://github.com/yuezhu1.png?size=160",
        "avatarSeed": "yuezhu1",
        "key": "github:yuezhu1",
        "reviews": 5,
        "merges": 2,
        "total": 7
      },
      {
        "rank": 8,
        "name": "Yehudit",
        "login": "yehuditkerido",
        "avatarLogin": "yehuditkerido",
        "avatarUrl": "https://github.com/yehuditkerido.png?size=160",
        "avatarSeed": "yehuditkerido",
        "key": "github:yehuditkerido",
        "reviews": 5,
        "merges": 0,
        "total": 5
      },
      {
        "rank": 9,
        "name": "cryo-zd",
        "login": "cryo-zd",
        "avatarLogin": "cryo-zd",
        "avatarUrl": "https://github.com/cryo-zd.png?size=160",
        "avatarSeed": "cryo-zd",
        "key": "github:cryo-zd",
        "reviews": 4,
        "merges": 0,
        "total": 4
      },
      {
        "rank": 10,
        "name": "aeft",
        "login": "aeft",
        "avatarLogin": "aeft",
        "avatarUrl": "https://github.com/aeft.png?size=160",
        "avatarSeed": "aeft",
        "key": "github:aeft",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 11,
        "name": "Yossi Ovadia",
        "login": "yossiovadia",
        "avatarLogin": "yossiovadia",
        "avatarUrl": "https://github.com/yossiovadia.png?size=160",
        "avatarSeed": "yossiovadia",
        "key": "github:yossiovadia",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 12,
        "name": "Liav Weiss",
        "login": "liavweiss",
        "avatarLogin": "liavweiss",
        "avatarUrl": "https://github.com/liavweiss.png?size=160",
        "avatarSeed": "liavweiss",
        "key": "github:liavweiss",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 13,
        "name": "Asaad Balum",
        "login": "asaadbalum",
        "avatarLogin": "asaadbalum",
        "avatarUrl": "https://github.com/asaadbalum.png?size=160",
        "avatarSeed": "asaadbalum",
        "key": "github:asaadbalum",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 14,
        "name": "carlory",
        "login": "carlory",
        "avatarLogin": "carlory",
        "avatarUrl": "https://github.com/carlory.png?size=160",
        "avatarSeed": "carlory",
        "key": "github:carlory",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 15,
        "name": "Noa Limoy",
        "login": "noalimoy",
        "avatarLogin": "noalimoy",
        "avatarUrl": "https://github.com/noalimoy.png?size=160",
        "avatarSeed": "noalimoy",
        "key": "github:noalimoy",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 16,
        "name": "Senan Zedan",
        "login": "szedan-rh",
        "avatarLogin": "szedan-rh",
        "avatarUrl": "https://github.com/szedan-rh.png?size=160",
        "avatarSeed": "szedan-rh",
        "key": "github:szedan-rh",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 17,
        "name": "Srinivas A",
        "login": "srini-abhiram",
        "avatarLogin": "srini-abhiram",
        "avatarUrl": "https://github.com/srini-abhiram.png?size=160",
        "avatarSeed": "srini-abhiram",
        "key": "github:srini-abhiram",
        "reviews": 1,
        "merges": 0,
        "total": 1
      }
    ]
  },
  "all": {
    "id": "all",
    "label": "All time",
    "generatedAt": "2026-07-13",
    "startDate": null,
    "endDate": "2026-07-13",
    "description": "Full committer review and merge history.",
    "activeCommitters": 26,
    "totalReviews": 389,
    "totalMerges": 116,
    "entries": [
      {
        "rank": 1,
        "name": "Aayush Saini",
        "login": "AayushSaini101",
        "avatarLogin": "AayushSaini101",
        "avatarUrl": "https://github.com/AayushSaini101.png?size=160",
        "avatarSeed": "AayushSaini101",
        "key": "github:aayushsaini101",
        "reviews": 41,
        "merges": 31,
        "total": 72
      },
      {
        "rank": 2,
        "name": "yuluo-yx",
        "login": "yuluo-yx",
        "avatarLogin": "yuluo-yx",
        "avatarUrl": "https://github.com/yuluo-yx.png?size=160",
        "avatarSeed": "yuluo-yx",
        "key": "github:yuluo-yx",
        "reviews": 58,
        "merges": 0,
        "total": 58
      },
      {
        "rank": 3,
        "name": "Hao Wu",
        "login": "haowu1234",
        "avatarLogin": "haowu1234",
        "avatarUrl": "https://github.com/haowu1234.png?size=160",
        "avatarSeed": "haowu1234",
        "key": "github:haowu1234",
        "reviews": 51,
        "merges": 7,
        "total": 58
      },
      {
        "rank": 4,
        "name": "JaredforReal",
        "login": "JaredforReal",
        "avatarLogin": "JaredforReal",
        "avatarUrl": "https://github.com/JaredforReal.png?size=160",
        "avatarSeed": "JaredforReal",
        "key": "github:jaredforreal",
        "reviews": 41,
        "merges": 13,
        "total": 54
      },
      {
        "rank": 5,
        "name": "FAUST",
        "login": "FAUST-BENCHOU",
        "avatarLogin": "FAUST-BENCHOU",
        "avatarUrl": "https://github.com/FAUST-BENCHOU.png?size=160",
        "avatarSeed": "FAUST-BENCHOU",
        "key": "github:faust-benchou",
        "reviews": 37,
        "merges": 11,
        "total": 48
      },
      {
        "rank": 6,
        "name": "samzong",
        "login": "samzong",
        "avatarLogin": "samzong",
        "avatarUrl": "https://github.com/samzong.png?size=160",
        "avatarSeed": "samzong",
        "key": "github:samzong",
        "reviews": 32,
        "merges": 14,
        "total": 46
      },
      {
        "rank": 7,
        "name": "WUKUNTAI",
        "login": "WUKUNTAI-0211",
        "avatarLogin": "WUKUNTAI-0211",
        "avatarUrl": "https://github.com/WUKUNTAI-0211.png?size=160",
        "avatarSeed": "WUKUNTAI-0211",
        "key": "github:wukuntai-0211",
        "reviews": 18,
        "merges": 19,
        "total": 37
      },
      {
        "rank": 8,
        "name": "yangw",
        "login": "drivebyer",
        "avatarLogin": "drivebyer",
        "avatarUrl": "https://github.com/drivebyer.png?size=160",
        "avatarSeed": "drivebyer",
        "key": "github:drivebyer",
        "reviews": 17,
        "merges": 13,
        "total": 30
      },
      {
        "rank": 9,
        "name": "Jintao Zhang",
        "login": "tao12345666333",
        "avatarLogin": "tao12345666333",
        "avatarUrl": "https://github.com/tao12345666333.png?size=160",
        "avatarSeed": "tao12345666333",
        "key": "github:tao12345666333",
        "reviews": 17,
        "merges": 0,
        "total": 17
      },
      {
        "rank": 10,
        "name": "Chen Wang",
        "login": "wangchen615",
        "avatarLogin": "wangchen615",
        "avatarUrl": "https://github.com/wangchen615.png?size=160",
        "avatarSeed": "wangchen615",
        "key": "github:wangchen615",
        "reviews": 10,
        "merges": 4,
        "total": 14
      },
      {
        "rank": 11,
        "name": "cryo-zd",
        "login": "cryo-zd",
        "avatarLogin": "cryo-zd",
        "avatarUrl": "https://github.com/cryo-zd.png?size=160",
        "avatarSeed": "cryo-zd",
        "key": "github:cryo-zd",
        "reviews": 8,
        "merges": 0,
        "total": 8
      },
      {
        "rank": 12,
        "name": "OneZero-Y",
        "login": "OneZero-Y",
        "avatarLogin": "OneZero-Y",
        "avatarUrl": "https://github.com/OneZero-Y.png?size=160",
        "avatarSeed": "OneZero-Y",
        "key": "github:onezero-y",
        "reviews": 8,
        "merges": 0,
        "total": 8
      },
      {
        "rank": 13,
        "name": "Yehudit",
        "login": "yehuditkerido",
        "avatarLogin": "yehuditkerido",
        "avatarUrl": "https://github.com/yehuditkerido.png?size=160",
        "avatarSeed": "yehuditkerido",
        "key": "github:yehuditkerido",
        "reviews": 8,
        "merges": 0,
        "total": 8
      },
      {
        "rank": 14,
        "name": "Senan Zedan",
        "login": "szedan-rh",
        "avatarLogin": "szedan-rh",
        "avatarUrl": "https://github.com/szedan-rh.png?size=160",
        "avatarSeed": "szedan-rh",
        "key": "github:szedan-rh",
        "reviews": 6,
        "merges": 1,
        "total": 7
      },
      {
        "rank": 15,
        "name": "Yue Zhu",
        "login": "yuezhu1",
        "avatarLogin": "yuezhu1",
        "avatarUrl": "https://github.com/yuezhu1.png?size=160",
        "avatarSeed": "yuezhu1",
        "key": "github:yuezhu1",
        "reviews": 5,
        "merges": 2,
        "total": 7
      },
      {
        "rank": 16,
        "name": "David Shrader",
        "login": "shraderdm",
        "avatarLogin": "shraderdm",
        "avatarUrl": "https://github.com/shraderdm.png?size=160",
        "avatarSeed": "shraderdm",
        "key": "github:shraderdm",
        "reviews": 6,
        "merges": 0,
        "total": 6
      },
      {
        "rank": 17,
        "name": "Liav Weiss",
        "login": "liavweiss",
        "avatarLogin": "liavweiss",
        "avatarUrl": "https://github.com/liavweiss.png?size=160",
        "avatarSeed": "liavweiss",
        "key": "github:liavweiss",
        "reviews": 5,
        "merges": 0,
        "total": 5
      },
      {
        "rank": 18,
        "name": "Abdallah Samara",
        "login": "abdallahsamabd",
        "avatarLogin": "abdallahsamabd",
        "avatarUrl": "https://github.com/abdallahsamabd.png?size=160",
        "avatarSeed": "abdallahsamabd",
        "key": "github:abdallahsamabd",
        "reviews": 4,
        "merges": 1,
        "total": 5
      },
      {
        "rank": 19,
        "name": "Qiping Pan",
        "login": "ppppqp",
        "avatarLogin": "ppppqp",
        "avatarUrl": "https://github.com/ppppqp.png?size=160",
        "avatarSeed": "ppppqp",
        "key": "github:ppppqp",
        "reviews": 4,
        "merges": 0,
        "total": 4
      },
      {
        "rank": 20,
        "name": "aeft",
        "login": "aeft",
        "avatarLogin": "aeft",
        "avatarUrl": "https://github.com/aeft.png?size=160",
        "avatarSeed": "aeft",
        "key": "github:aeft",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 21,
        "name": "Yossi Ovadia",
        "login": "yossiovadia",
        "avatarLogin": "yossiovadia",
        "avatarUrl": "https://github.com/yossiovadia.png?size=160",
        "avatarSeed": "yossiovadia",
        "key": "github:yossiovadia",
        "reviews": 3,
        "merges": 0,
        "total": 3
      },
      {
        "rank": 22,
        "name": "Asaad Balum",
        "login": "asaadbalum",
        "avatarLogin": "asaadbalum",
        "avatarUrl": "https://github.com/asaadbalum.png?size=160",
        "avatarSeed": "asaadbalum",
        "key": "github:asaadbalum",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 23,
        "name": "Noa Limoy",
        "login": "noalimoy",
        "avatarLogin": "noalimoy",
        "avatarUrl": "https://github.com/noalimoy.png?size=160",
        "avatarSeed": "noalimoy",
        "key": "github:noalimoy",
        "reviews": 2,
        "merges": 0,
        "total": 2
      },
      {
        "rank": 24,
        "name": "carlory",
        "login": "carlory",
        "avatarLogin": "carlory",
        "avatarUrl": "https://github.com/carlory.png?size=160",
        "avatarSeed": "carlory",
        "key": "github:carlory",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 25,
        "name": "siloteemu",
        "login": "siloteemu",
        "avatarLogin": "siloteemu",
        "avatarUrl": "https://github.com/siloteemu.png?size=160",
        "avatarSeed": "siloteemu",
        "key": "github:siloteemu",
        "reviews": 1,
        "merges": 0,
        "total": 1
      },
      {
        "rank": 26,
        "name": "Srinivas A",
        "login": "srini-abhiram",
        "avatarLogin": "srini-abhiram",
        "avatarUrl": "https://github.com/srini-abhiram.png?size=160",
        "avatarSeed": "srini-abhiram",
        "key": "github:srini-abhiram",
        "reviews": 1,
        "merges": 0,
        "total": 1
      }
    ]
  }
} satisfies Record<CommitterStatsRange, CommitterStatsSnapshot>
