# Recipe: Accuracy-Optimized Configuration
# Objective: Maximum accuracy and response quality
# Trade-offs: Higher token usage, increased latency, more computational cost
# Use case: Research, critical decision-making, high-stakes applications
#
# Key optimizations:
# - Reasoning enabled for most complex categories
# - High reasoning effort level (high)
# - Strict classification thresholds (higher confidence required)
# - Semantic cache disabled to ensure fresh responses
# - Tool selection enabled with broad matching
# - PII detection strict for safety
# - Jailbreak protection enabled

bert_model:
  model_id: models/all-MiniLM-L12-v2
  threshold: 0.7  # Higher threshold for better precision
  use_cpu: true

semantic_cache:
  enabled: false  # Disable caching to ensure fresh, accurate responses
  backend_type: "memory"
  similarity_threshold: 0.95  # Very high threshold if cache is enabled
  max_entries: 500
  ttl_seconds: 1800  # Shorter TTL for fresher results
  eviction_policy: "lru"

tools:
  enabled: true  # Enable tools for comprehensive responses
  top_k: 5  # Select more tools for better coverage
  similarity_threshold: 0.15  # Lower threshold to include more relevant tools
  tools_db_path: "config/tools_db.json"
  fallback_to_empty: true

prompt_guard:
  enabled: true  # Enable for safety
  use_modernbert: true
  model_id: "models/jailbreak_classifier_modernbert-base_model"
  threshold: 0.65  # Lower threshold (more sensitive detection)
  use_cpu: true
  jailbreak_mapping_path: "models/jailbreak_classifier_modernbert-base_model/jailbreak_type_mapping.json"

vllm_endpoints:
  - name: "endpoint1"
    address: "127.0.0.1"
    port: 8000
    weight: 1

model_config:
  "openai/gpt-oss-20b":
    reasoning_family: "gpt-oss"
    preferred_endpoints: ["endpoint1"]
    pii_policy:
      allow_by_default: false  # Strict PII policy for safety
      pii_types_allowed: []  # No PII allowed by default
    pricing:
      currency: USD
      prompt_per_1m: 0.10
      completion_per_1m: 0.30

classifier:
  category_model:
    model_id: "models/category_classifier_modernbert-base_model"
    use_modernbert: true
    threshold: 0.7  # Higher threshold for confident classification
    use_cpu: true
    category_mapping_path: "models/category_classifier_modernbert-base_model/category_mapping.json"
  pii_model:
    model_id: "models/pii_classifier_modernbert-base_presidio_token_model"
    use_modernbert: true
    threshold: 0.6  # Lower threshold for sensitive PII detection
    use_cpu: true
    pii_mapping_path: "models/pii_classifier_modernbert-base_presidio_token_model/pii_type_mapping.json"

categories:
  - name: business
    system_prompt: "You are a senior business consultant and strategic advisor with expertise in corporate strategy, operations management, financial analysis, marketing, and organizational development. Provide practical, actionable business advice backed by proven methodologies and industry best practices. Consider market dynamics, competitive landscape, and stakeholder interests in your recommendations."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for better business analysis
  - name: law
    system_prompt: "You are a knowledgeable legal expert with comprehensive understanding of legal principles, case law, statutory interpretation, and legal procedures across multiple jurisdictions. Provide accurate legal information and analysis while clearly stating that your responses are for informational purposes only and do not constitute legal advice. Always recommend consulting with qualified legal professionals for specific legal matters."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for legal analysis
  - name: psychology
    system_prompt: "You are a psychology expert with deep knowledge of cognitive processes, behavioral patterns, mental health, developmental psychology, social psychology, and therapeutic approaches. Provide evidence-based insights grounded in psychological research and theory. When discussing mental health topics, emphasize the importance of professional consultation and avoid providing diagnostic or therapeutic advice."
    # Category-level cache override (if global cache is enabled)
    # semantic_cache_enabled: true
    # semantic_cache_similarity_threshold: 0.92  # Strict for clinical nuances
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for psychological analysis
  - name: biology
    system_prompt: "You are a biology expert with comprehensive knowledge spanning molecular biology, genetics, cell biology, ecology, evolution, anatomy, physiology, and biotechnology. Explain biological concepts with scientific accuracy, use appropriate terminology, and provide examples from current research. Connect biological principles to real-world applications and emphasize the interconnectedness of biological systems."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for scientific rigor
  - name: chemistry
    system_prompt: "You are a chemistry expert specializing in chemical reactions, molecular structures, and laboratory techniques. Provide detailed, step-by-step explanations."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for complex chemistry
  - name: history
    system_prompt: "You are a historian with expertise across different time periods and cultures. Provide accurate historical context and analysis."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for historical analysis
  - name: other
    system_prompt: "You are a helpful and knowledgeable assistant. Provide accurate, helpful responses across a wide range of topics."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.9
        use_reasoning: false  # Default queries don't need reasoning
  - name: health
    system_prompt: "You are a health and medical information expert with knowledge of anatomy, physiology, diseases, treatments, preventive care, nutrition, and wellness. Provide accurate, evidence-based health information while emphasizing that your responses are for educational purposes only and should never replace professional medical advice, diagnosis, or treatment. Always encourage users to consult healthcare professionals for medical concerns and emergencies."
    # Category-level cache override (if global cache is enabled)
    # semantic_cache_enabled: true
    # semantic_cache_similarity_threshold: 0.95  # Very strict - medical accuracy critical
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for medical accuracy
  - name: economics
    system_prompt: "You are an economics expert with deep understanding of microeconomics, macroeconomics, econometrics, financial markets, monetary policy, fiscal policy, international trade, and economic theory. Analyze economic phenomena using established economic principles, provide data-driven insights, and explain complex economic concepts in accessible terms. Consider both theoretical frameworks and real-world applications in your responses."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for economic analysis
  - name: math
    system_prompt: "You are a mathematics expert. Provide step-by-step solutions, show your work clearly, and explain mathematical concepts in an understandable way."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for complex math
  - name: physics
    system_prompt: "You are a physics expert with deep understanding of physical laws and phenomena. Provide clear explanations with mathematical derivations when appropriate."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for physics
  - name: computer science
    system_prompt: "You are a computer science expert with knowledge of algorithms, data structures, programming languages, and software engineering. Provide clear, practical solutions with code examples when helpful."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for complex CS problems
  - name: philosophy
    system_prompt: "You are a philosophy expert with comprehensive knowledge of philosophical traditions, ethical theories, logic, metaphysics, epistemology, political philosophy, and the history of philosophical thought. Engage with complex philosophical questions by presenting multiple perspectives, analyzing arguments rigorously, and encouraging critical thinking. Draw connections between philosophical concepts and contemporary issues while maintaining intellectual honesty about the complexity and ongoing nature of philosophical debates."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for philosophical inquiry
  - name: engineering
    system_prompt: "You are an engineering expert with knowledge across multiple engineering disciplines including mechanical, electrical, civil, chemical, software, and systems engineering. Apply engineering principles, design methodologies, and problem-solving approaches to provide practical solutions. Consider safety, efficiency, sustainability, and cost-effectiveness in your recommendations. Use technical precision while explaining concepts clearly, and emphasize the importance of proper engineering practices and standards."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 1.0
        use_reasoning: true  # Enable reasoning for engineering analysis

default_model: openai/gpt-oss-20b

reasoning_families:
  deepseek:
    type: "chat_template_kwargs"
    parameter: "thinking"
  qwen3:
    type: "chat_template_kwargs"
    parameter: "enable_thinking"
  gpt-oss:
    type: "reasoning_effort"
    parameter: "reasoning_effort"
  gpt:
    type: "reasoning_effort"
    parameter: "reasoning_effort"

default_reasoning_effort: high  # Maximum reasoning effort

api:
  batch_classification:
    max_batch_size: 50  # Smaller batches for more accurate processing
    concurrency_threshold: 3
    max_concurrency: 4
    metrics:
      enabled: true
      detailed_goroutine_tracking: true
      high_resolution_timing: true
      sample_rate: 1.0
      duration_buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60]
      size_buckets: [1, 2, 5, 10, 20, 50, 100]

observability:
  tracing:
    enabled: true  # Enable for monitoring accuracy
    provider: "opentelemetry"
    exporter:
      type: "otlp"
      endpoint: "localhost:4317"
      insecure: true
    sampling:
      type: "always_on"
      rate: 1.0
    resource:
      service_name: "vllm-semantic-router-accuracy"
      service_version: "v0.1.0"
      deployment_environment: "production"
