bert_model:
  model_id: sentence-transformers/all-MiniLM-L12-v2
  threshold: 0.6
  use_cpu: true
semantic_cache:
  enabled: true
  backend_type: "memory"  # Options: "memory" or "milvus"
  similarity_threshold: 0.8
  max_entries: 1000  # Only applies to memory backend
  ttl_seconds: 3600

  # For production environments, use Milvus for scalable caching:
  # backend_type: "milvus"
  # backend_config_path: "config/cache/milvus.yaml"

  # Development/Testing: Use in-memory cache (current configuration)
  # - Fast startup and no external dependencies
  # - Limited to single instance scaling
  # - Data lost on restart

  # Production: Use Milvus vector database
  # - Horizontally scalable and persistent
  # - Supports distributed deployments
  # - Requires Milvus cluster setup
  # - To enable: uncomment the lines above and install Milvus dependencies
tools:
  enabled: true  # Set to true to enable automatic tool selection
  top_k: 3        # Number of most relevant tools to select
  similarity_threshold: 0.2  # Threshold for tool similarity
  tools_db_path: "config/tools_db.json"
  fallback_to_empty: true  # If true, return no tools on failure; if false, return error
prompt_guard:
  enabled: true
  use_modernbert: true
  model_id: "models/jailbreak_classifier_modernbert-base_model"
  threshold: 0.7
  use_cpu: true
  jailbreak_mapping_path: "models/jailbreak_classifier_modernbert-base_model/jailbreak_type_mapping.json"

# vLLM Endpoints Configuration - supports multiple endpoints, each can serve multiple models
vllm_endpoints:
  - name: "qwen-endpoint"
    address: "127.0.0.1"
    port: 8000
    models:
      - "Model-A"
    weight: 1
    health_check_path: "/health"
  - name: "tinyllama-endpoint"
    address: "127.0.0.1"
    port: 8001
    models:
      - "Model-B"
    weight: 1
    health_check_path: "/health"

model_config:

  "Model-A":
    use_reasoning: false
    reasoning_family: "qwen3"  # This model uses Qwen reasoning syntax
    preferred_endpoints: ["qwen-endpoint"]
    pii_policy:
      allow_by_default: false  # Strict PII blocking model
      pii_types_allowed: ["EMAIL_ADDRESS"]  # Only allow emails
  "Model-B":
    use_reasoning: false
    preferred_endpoints: ["tinyllama-endpoint"]
    pii_policy:
      allow_by_default: true  # Permissive PII model for safe routing
      pii_types_allowed: ["EMAIL_ADDRESS", "PERSON", "GPE", "PHONE_NUMBER", "US_SSN", "CREDIT_CARD"]

# Classifier configuration for text classification
classifier:
  category_model:
    model_id: "models/category_classifier_modernbert-base_model"  # TODO: Use local model for now before the code can download the entire model from huggingface
    use_modernbert: true
    threshold: 0.6
    use_cpu: true
    category_mapping_path: "models/category_classifier_modernbert-base_model/category_mapping.json"
  pii_model:
    model_id: "models/pii_classifier_modernbert-base_presidio_token_model"  # TODO: Use local model for now before the code can download the entire model from huggingface
    use_modernbert: true
    threshold: 0.7
    use_cpu: true
    pii_mapping_path: "models/pii_classifier_modernbert-base_presidio_token_model/pii_type_mapping.json"
categories:
  - name: business
    model_scores:
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Business content is typically conversational"
        reasoning_effort: low
      - model: "Model-B"
        score: 0.4
        use_reasoning: false
      - model: "Model-A"
        score: 0.2
        use_reasoning: false
  - name: law
    model_scores:
      - model: "Model-B"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Legal content is typically explanatory"
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.4
        use_reasoning: false
  - name: psychology
    model_scores:
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
        reasoning_description: "Psychology content is usually explanatory"
      - model: "Model-B"
        score: 0.4
        use_reasoning: false
      - model: "Model-A"
        score: 0.4
        use_reasoning: false
  - name: biology
    model_scores:
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Biological processes benefit from structured analysis"
      - model: "Model-B"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.2
        use_reasoning: false
  - name: chemistry
    model_scores:
      - model: "Model-A"
        score: 0.8
        use_reasoning: true
        reasoning_description: "Chemical reactions and formulas require systematic thinking"
        reasoning_effort: high
      - model: "Model-B"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
  - name: history
    model_scores:
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Historical content is narrative-based"
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
      - model: "Model-B"
        score: 0.4
        use_reasoning: false
  - name: other
    model_scores:
      - model: "Model-B"
        score: 0.8
        use_reasoning: false
        reasoning_description: "General content doesn't require reasoning"
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
  - name: health
    model_scores:
      - model: "Model-B"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Health information is typically informational"
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
  - name: economics
    model_scores:
      - model: "Model-B"
        score: 0.8
        use_reasoning: false
        reasoning_description: "Economic discussions are usually explanatory"
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
      - model: "Model-A"
        score: 0.1
        use_reasoning: false
  - name: math
    model_scores:
      - model: "Model-B"
        score: 1.0
        use_reasoning: true
        reasoning_description: "Mathematical problems require step-by-step reasoning"
        reasoning_effort: high
      - model: "Model-A"
        score: 0.9
        use_reasoning: true
        reasoning_description: "Mathematical problems require step-by-step reasoning"
        reasoning_effort: high
      - model: "Model-A"
        score: 0.8
        use_reasoning: false
      - model: "Model-B"
        score: 0.6
        use_reasoning: false
  - name: physics
    model_scores:
      - model: "Model-B"
        score: 0.4
        use_reasoning: true
        reasoning_description: "Physics concepts need logical analysis"
      - model: "Model-A"
        score: 0.4
        use_reasoning: false
      - model: "Model-A"
        score: 0.4
        use_reasoning: false
  - name: computer science
    model_scores:
      - model: "Model-B"
        score: 0.6
        use_reasoning: false
        reasoning_description: "Programming and algorithms need logical reasoning"
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.1
        use_reasoning: false
  - name: philosophy
    model_scores:
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
        reasoning_description: "Philosophical discussions are conversational"
      - model: "Model-B"
        score: 0.2
        use_reasoning: false
      - model: "Model-A"
        score: 0.2
        use_reasoning: false
  - name: engineering
    model_scores:
      - model: "Model-B"
        score: 0.6
        use_reasoning: false
        reasoning_description: "Engineering problems require systematic problem-solving"
      - model: "Model-A"
        score: 0.6
        use_reasoning: false
      - model: "Model-A"
        score: 0.2
        use_reasoning: false

default_model: "Model-A"

# API Configuration
api:
  batch_classification:
    # Metrics configuration for monitoring batch classification performance
    metrics:
      enabled: true              # Enable comprehensive metrics collection
      detailed_goroutine_tracking: true  # Track individual goroutine lifecycle
      high_resolution_timing: false      # Use nanosecond precision timing
      sample_rate: 1.0                   # Collect metrics for all requests (1.0 = 100%, 0.5 = 50%)
      # Histogram buckets for metrics (directly configure what you need)
      duration_buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30]
      size_buckets: [1, 2, 5, 10, 20, 50, 100, 200]

# Reasoning family configurations - define how different model families handle reasoning syntax
reasoning_families:
  deepseek:
    type: "chat_template_kwargs"
    parameter: "thinking"

  qwen3:
    type: "chat_template_kwargs"
    parameter: "enable_thinking"

  gpt-oss:
    type: "reasoning_effort"
    parameter: "reasoning_effort"

  gpt:
    type: "reasoning_effort"
    parameter: "reasoning_effort"

# Global default reasoning effort level
default_reasoning_effort: medium  # Default reasoning effort level (low, medium, high)
