#!/usr/bin/env bash

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
output=${1:-website/docs/api/crd-reference.md}
tool=${CRD_REF_DOCS_BIN:-crd-ref-docs}

if [[ "$output" != /* ]]; then
  output="$repo_root/$output"
fi

tmp_dir=$(mktemp -d)
trap 'rm -rf -- "$tmp_dir"' EXIT

cd "$repo_root"
"$tool" \
  --source-path=./deploy/operator/api/v1alpha1 \
  --config=tools/crd/ref-docs.yaml \
  --max-depth=20 \
  --renderer=markdown \
  --output-path="$tmp_dir/body.md"

{
  printf '%s\n' \
    '---' \
    'title: Generated SemanticRouter CRD Fields' \
    'sidebar_label: Generated CRD Fields' \
    'description: Generated field-level API reference for the current vllm.ai/v1alpha1 SemanticRouter custom resource.' \
    '---' \
    '' \
    '<!-- Generated by make docs-crd. Do not edit by hand. -->' \
    ''
  cat "$tmp_dir/body.md"
} >"$tmp_dir/reference.raw.md"

# crd-ref-docs emits extra blank lines and places generated lists directly
# against surrounding headings and paragraphs. Normalize only that mechanical
# whitespace so the generated page satisfies the repository Markdown rules.
python3 - "$tmp_dir/reference.raw.md" "$tmp_dir/reference.md" <<'PY'
from pathlib import Path
import re
import sys

source = Path(sys.argv[1]).read_text(encoding="utf-8").splitlines()
collapsed: list[str] = []
for line in source:
    line = line.rstrip()
    if line or not collapsed or collapsed[-1]:
        collapsed.append(line)

formatted: list[str] = []
list_item = re.compile(r"^\s*[-*+]\s+")
for line in collapsed:
    current_is_list = bool(list_item.match(line))
    previous_is_list = bool(formatted and list_item.match(formatted[-1]))
    if current_is_list and formatted and formatted[-1] and not previous_is_list:
        formatted.append("")
    elif not current_is_list and line and previous_is_list:
        formatted.append("")
    formatted.append(line)

while formatted and not formatted[-1]:
    formatted.pop()
Path(sys.argv[2]).write_text("\n".join(formatted) + "\n", encoding="utf-8")
PY

install -m 0644 "$tmp_dir/reference.md" "$output"
