apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-pipelines
  labels:
    app: openwebui-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui-pipelines
  template:
    metadata:
      labels:
        app: openwebui-pipelines
    spec:
      containers:
        - name: pipelines
          image: ghcr.io/open-webui/pipelines:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9099
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PIPELINES_DIR
              value: "/app/pipelines"
          volumeMounts:
            # Writable directory for pipelines runtime
            - name: pipelines-data
              mountPath: /app/pipelines
            # Mount our pipeline file from ConfigMap into the writable dir
            - name: pipelines-config
              mountPath: /app/pipelines/vllm_semantic_router_pipe.py
              subPath: vllm_semantic_router_pipe.py
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: pipelines-data
          emptyDir: {}
        - name: pipelines-config
          configMap:
            name: openwebui-pipelines-config
