# PV for Models
apiVersion: v1
kind: PersistentVolume
metadata:
  name: semantic-router-models-pv
  labels:
    app: semantic-router
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/models
    type: DirectoryOrCreate
---
# PVC for Models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semantic-router-models
  namespace: vllm-semantic-router-system
  labels:
    app: semantic-router
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  volumeName: semantic-router-models-pv
