apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm-semantic-router-system

commonLabels:
  app.kubernetes.io/part-of: semantic-router-stack
  app.kubernetes.io/component: observability

resources:
  # Prometheus
  - prometheus/rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/pvc.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/route.yaml

  # Grafana
  - grafana/secret.yaml
  - grafana/configmap-datasource.yaml
  - grafana/configmap-provisioning.yaml
  - grafana/configmap-dashboard.yaml
  - grafana/pvc.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/route.yaml
