apiVersion: v2
name: semantic-router
description: A Helm chart for deploying Semantic Router - an intelligent routing system for LLM applications
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - semantic-router
  - llm
  - vllm
  - ai
  - routing
  - classification
home: https://github.com/vllm-project/semantic-router
sources:
  - https://github.com/vllm-project/semantic-router
maintainers:
  - name: Semantic Router Team
    url: https://github.com/vllm-project/semantic-router
icon: https://raw.githubusercontent.com/vllm-project/semantic-router/main/website/static/img/logo.png
