# Development environment values
# Optimized for local development with reduced resources

replicaCount: 1

image:
  pullPolicy: Always
  tag: "latest"

# Reduced resources for development
resources:
  limits:
    memory: "4Gi"
    cpu: "1"
  requests:
    memory: "2Gi"
    cpu: "500m"

initContainer:
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
    requests:
      memory: "256Mi"
      cpu: "100m"

# Smaller storage for development
persistence:
  size: 5Gi
  storageClassName: "standard"

# Faster probes for development
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Development configuration
config:
  bert_model:
    use_cpu: true
    threshold: 0.5  # Lower threshold for testing

  semantic_cache:
    enabled: true
    max_entries: 500  # Smaller cache for dev

  tools:
    enabled: true

  prompt_guard:
    enabled: true
    use_cpu: true

  vllm_endpoints:
    - name: "dev-endpoint"
      address: "127.0.0.1"
      port: 8000
      weight: 1

  # Enable detailed metrics for debugging
  api:
    batch_classification:
      metrics:
        enabled: true
        detailed_goroutine_tracking: true
        high_resolution_timing: true
        sample_rate: 1.0

# Disable autoscaling in development
autoscaling:
  enabled: false

# Ingress disabled for local development
ingress:
  enabled: false

# Service type for local development
service:
  type: ClusterIP
