# Copyright 2025 The vLLM Semantic Router Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example: Using generic categories with MMLU-Pro mapping
# This file demonstrates how to declare free-style categories and map them to
# MMLU-Pro categories expected by the classifier model.

bert_model:
  model_id: sentence-transformers/all-MiniLM-L12-v2
  threshold: 0.6
  use_cpu: true

classifier:
  category_model:
    model_id: "models/category_classifier_modernbert-base_model"
    use_modernbert: true
    threshold: 0.6
    use_cpu: true
    category_mapping_path: "models/category_classifier_modernbert-base_model/category_mapping.json"

# Define your generic categories and map them to MMLU-Pro categories.
# The classifier will translate predicted MMLU categories into these generic names.
categories:
  - name: tech
    mmlu_categories: ["computer science", "engineering"]
    model_scores:
      - model: phi4
        score: 0.9
      - model: mistral-small3.1
        score: 0.7
  - name: finance
    mmlu_categories: ["economics"]
    model_scores:
      - model: gemma3:27b
        score: 0.8
  - name: politics
    # If omitted, identity mapping applies when this name matches MMLU
    model_scores:
      - model: gemma3:27b
        score: 0.6

# A default model is recommended for fallback
default_model: mistral-small3.1
