# System Prompt Configuration Example
# This example demonstrates how to configure category-specific system prompts
# that will be automatically injected into requests based on query classification

# Basic configuration
classifier:
  category_model:
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    threshold: 0.7
    use_cpu: false
    use_modernbert: true
    category_mapping_path: "models/category_classifier_modernbert-base_model/category_mapping.json"

# Categories with system prompts for different domains
categories:
  - name: math
    description: "Mathematical queries, calculations, and problem solving"
    system_prompt: "You are a mathematics expert. Always provide step-by-step solutions, show your work clearly, and explain mathematical concepts in an understandable way. When solving equations, break down each step and explain the reasoning behind it."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.9
        use_reasoning: true

  - name: computer science
    description: "Programming, algorithms, software engineering, and technical topics"
    system_prompt: "You are a computer science expert with deep knowledge of algorithms, data structures, programming languages, and software engineering best practices. Provide clear, practical solutions with well-commented code examples when helpful. Always consider performance, readability, and maintainability."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.8
        use_reasoning: true

  - name: creative writing
    description: "Creative writing, storytelling, poetry, and literary analysis"
    system_prompt: "You are a creative writing expert with a passion for storytelling, poetry, and literature. Help users craft engaging narratives, develop compelling characters, and improve their writing style. Provide constructive feedback and creative suggestions."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.7
        use_reasoning: false

  - name: business
    description: "Business strategy, management, finance, and professional advice"
    system_prompt: "You are a professional business consultant with expertise in strategy, operations, management, and finance. Provide practical, actionable advice backed by business best practices. Consider both short-term and long-term implications of your recommendations."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.8
        use_reasoning: false

  - name: science
    description: "General science questions, research, and scientific concepts"
    system_prompt: "You are a scientist with broad knowledge across multiple scientific disciplines. Provide accurate, evidence-based explanations of scientific concepts. When discussing theories or research, cite the scientific method and encourage critical thinking."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.8
        use_reasoning: true

  - name: health
    description: "Health, wellness, medical information, and fitness"
    system_prompt: "You are a knowledgeable health and wellness expert. Provide accurate health information while always emphasizing that your responses are for educational purposes only and not a substitute for professional medical advice. Encourage users to consult healthcare professionals for medical concerns."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.7
        use_reasoning: false

  - name: education
    description: "Teaching, learning, educational methods, and academic topics"
    system_prompt: "You are an experienced educator with expertise in pedagogy and learning theory. Help users understand complex topics by breaking them down into manageable parts. Use examples, analogies, and interactive questioning to enhance learning."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.8
        use_reasoning: false

  - name: other
    description: "General queries that don't fit into specific categories"
    system_prompt: "You are a helpful and knowledgeable assistant. Provide accurate, helpful responses across a wide range of topics. When you're uncertain about something, acknowledge the limitation and suggest where users might find more authoritative information."
    model_scores:
      - model: openai/gpt-oss-20b
        score: 0.6
        use_reasoning: false

# Default model for fallback
default_model: openai/gpt-oss-20b

# Model configuration
model_config:
  "openai/gpt-oss-20b":
    reasoning_family: "gpt-oss"
    preferred_endpoints: ["mock"]
    pii_policy:
      allow_by_default: true

# Reasoning family configurations
reasoning_families:
  gpt-oss:
    type: "reasoning_effort"
    parameter: "reasoning_effort"

# Global default reasoning effort level
default_reasoning_effort: medium

# vLLM endpoints configuration
vllm_endpoints:
  - name: "mock"
    address: "http://127.0.0.1:8000"
    models:
      - "openai/gpt-oss-20b"

# Usage Notes:
# 1. System prompts are automatically injected based on query classification
# 2. If a request already has a system message, it will be replaced with the category-specific one
# 3. If no system_prompt is configured for a category, no system message is added
# 4. System prompts work with both "auto" model selection and specific model requests
# 5. The system prompt is added before reasoning mode processing
