apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: vllm-llama3-8b-instruct
spec:
  targetPorts:
  - number: 8000
  selector:
    matchLabels:
      app: vllm-llama3-8b-instruct
  endpointPickerRef:
    name: vllm-llama3-8b-instruct-epp
    kind: Service
    port:
      number: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama3-8b-instruct-epp
spec:
  selector:
    app: vllm-llama3-8b-instruct-epp
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: http2
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-llama3-8b-instruct-epp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-d-inference-scheduler-llama3-8b
  labels:
    app: vllm-llama3-8b-instruct-epp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-llama3-8b-instruct-epp
  template:
    metadata:
      labels:
        app: vllm-llama3-8b-instruct-epp
    spec:
      serviceAccountName: vllm-llama3-8b-instruct-epp
      terminationGracePeriodSeconds: 130
      containers:
      - name: epp
        image: ghcr.io/llm-d/llm-d-router-endpoint-picker:v0.10.0
        imagePullPolicy: Always
        args:
        - --pool-name
        - vllm-llama3-8b-instruct
        - --pool-namespace
        - default
        - --pool-group
        - inference.networking.k8s.io
        - --v
        - '4'
        - --zap-encoder
        - json
        - --grpc-port
        - '9002'
        - --grpc-health-port
        - '9003'
        - --config-file
        - /config/default-plugins.yaml
        - --metrics-endpoint-auth=false
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: plugins-config-volume
          mountPath: /config
      volumes:
      - name: plugins-config-volume
        configMap:
          name: plugins-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins-config
data:
  default-plugins.yaml: |
    apiVersion: llm-d.ai/v1alpha1
    kind: EndpointPickerConfig
    plugins:
    - type: queue-scorer
    - type: kv-cache-utilization-scorer
    - type: prefix-cache-scorer
    - type: metrics-data-source
      parameters:
        scheme: http
        path: /metrics
        insecureSkipVerify: true
    - type: core-metrics-extractor
    schedulingProfiles:
    - name: default
      plugins:
      - pluginRef: queue-scorer
        weight: 2
      - pluginRef: kv-cache-utilization-scorer
        weight: 2
      - pluginRef: prefix-cache-scorer
        weight: 3
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read
rules:
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferenceobjectives
  - inferencemodelrewrites
  - inferencepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - llm-d.ai
  resources:
  - inferenceobjectives
  - inferencemodelrewrites
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - inference.networking.k8s.io
  resources:
  - inferenceobjectives
  - inferencepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-read-binding-llama
subjects:
- kind: ServiceAccount
  name: vllm-llama3-8b-instruct-epp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-read
