package config

import (
	"reflect"
	"testing"
)

// A configuration that declares no domains gets one per name its decisions
// reference. A classifier label declares itself; any other name lists other.
func TestAutoGeneratedDomainsMapTheirOwnLabels(t *testing.T) {
	cfg, err := ParseYAMLBytes([]byte(`
version: v0.3
listeners:
  - name: http-8899
    address: 0.0.0.0
    port: 8899
providers:
  defaults:
    model: m
  models:
    - name: m
      backend_refs:
        - endpoint: 127.0.0.1:8000
routing:
  modelCards:
    - name: m
  decisions:
    - name: maths
      rules:
        operator: OR
        conditions:
          - type: domain
            name: math
          - type: domain
            name: computer science
      modelRefs:
        - model: m
    - name: coding
      rules:
        operator: AND
        conditions:
          - type: domain
            name: coding
      modelRefs:
        - model: m
`))
	if err != nil {
		t.Fatal(err)
	}
	got := map[string][]string{}
	for _, category := range cfg.Categories {
		got[category.Name] = category.MMLUCategories
	}
	want := map[string][]string{
		"coding":           {"other"},
		"computer science": {"computer science"},
		"math":             {"math"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("auto-generated domains = %v, want %v", got, want)
	}
}
