package config

import (
	"strings"
	"testing"
)

// Regression tests for the global-namespace contracts across recipes: the
// flat decision gate, the by-name decision lookup, decision-name uniqueness,
// auto-generated signal merging, and entrypoint-name collisions.

const recipesOnlyConfigYAML = `
version: v0.3
routing:
  modelCards:
    - name: model-a
      description: default tier
    - name: model-b
      description: privacy tier
recipes:
  - name: privacy
    description: privacy profile
    routing:
      signals:
        keywords:
          - name: pii_keywords
            operator: OR
            keywords: ["ssn"]
      decisions:
        - name: privacy_route
          rules:
            operator: AND
            conditions:
              - type: keyword
                name: pii_keywords
          modelRefs:
            - model: model-b
              use_reasoning: false
entrypoints:
  - model_names: ["vllm-sr/privacy"]
    recipe: privacy
providers:
  defaults:
    default_model: model-a
  models:
    - name: model-a
      backend_refs:
        - endpoint: 127.0.0.1:8000
    - name: model-b
      backend_refs:
        - endpoint: 127.0.0.1:8001
`

func TestRecipesOnlyConfigKeepsDecisionsReachable(t *testing.T) {
	cfg, err := ParseYAMLBytes([]byte(recipesOnlyConfigYAML))
	if err != nil {
		t.Fatalf("unexpected parse error: %v", err)
	}

	if len(cfg.DefaultDecisions) != 0 {
		t.Fatalf("expected no flat decisions in a recipes-only config, got %d", len(cfg.DefaultDecisions))
	}
	if !cfg.HasRoutingDecisions() {
		t.Fatal("HasRoutingDecisions must see decisions living in non-default recipes")
	}
	decision := cfg.GetDecisionByName("privacy_route")
	if decision == nil {
		t.Fatal("GetDecisionByName must find decisions living in non-default recipes")
	}
	if decision.Name != "privacy_route" {
		t.Fatalf("expected privacy_route, got %q", decision.Name)
	}
}

func TestSharedAutoGeneratedDomainCategoryMergesAcrossRecipes(t *testing.T) {
	yamlConfig := `
version: v0.3
routing:
  modelCards:
    - name: model-a
      description: default tier
    - name: model-b
      description: privacy tier
  decisions:
    - name: math_default
      rules:
        operator: AND
        conditions:
          - type: domain
            name: math
      modelRefs:
        - model: model-a
          use_reasoning: false
recipes:
  - name: privacy
    routing:
      decisions:
        - name: math_privacy
          rules:
            operator: AND
            conditions:
              - type: domain
                name: math
          modelRefs:
            - model: model-b
              use_reasoning: false
providers:
  defaults:
    default_model: model-a
  models:
    - name: model-a
      backend_refs:
        - endpoint: 127.0.0.1:8000
    - name: model-b
      backend_refs:
        - endpoint: 127.0.0.1:8001
`
	cfg, err := ParseYAMLBytes([]byte(yamlConfig))
	if err != nil {
		t.Fatalf("two profiles routing on the same domain must load: %v", err)
	}

	mathCategories := 0
	for _, category := range cfg.Categories {
		if category.Name == "math" {
			mathCategories++
		}
	}
	if mathCategories != 1 {
		t.Fatalf("expected the identical auto-generated math category to merge once, got %d entries", mathCategories)
	}
}

func TestDuplicateDecisionNameAcrossRecipesRejected(t *testing.T) {
	yamlConfig := recipeTestBaseYAML + `
recipes:
  - name: privacy
    routing:
      signals:
        keywords:
          - name: pii_keywords
            operator: OR
            keywords: ["ssn"]
      decisions:
        - name: default_route
          rules:
            operator: AND
            conditions:
              - type: keyword
                name: pii_keywords
          modelRefs:
            - model: model-b
              use_reasoning: false
`
	_, err := ParseYAMLBytes([]byte(yamlConfig))
	if err == nil {
		t.Fatal("expected a duplicate decision name across recipes to be rejected")
	}
	if !strings.Contains(err.Error(), `decision "default_route" is defined by both`) {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCaseAliasedDecisionNameAcrossRecipesRejected(t *testing.T) {
	yamlConfig := recipeTestBaseYAML + `
recipes:
  - name: privacy
    routing:
      signals:
        keywords:
          - name: pii_keywords
            operator: OR
            keywords: ["ssn"]
      decisions:
        - name: Default_Route
          rules:
            operator: AND
            conditions:
              - type: keyword
                name: pii_keywords
          modelRefs:
            - model: model-b
              use_reasoning: false
`
	_, err := ParseYAMLBytes([]byte(yamlConfig))
	if err == nil {
		t.Fatal("expected a case-aliased decision name across recipes to be rejected: GetDecisionByNameFold would treat the two as one")
	}
	if !strings.Contains(err.Error(), `differs only by case`) {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestEntrypointNameCollisionsRejected(t *testing.T) {
	cases := []struct {
		name          string
		entrypoint    string
		wantErrSubstr string
	}{
		{
			name:          "configured model",
			entrypoint:    "model-a",
			wantErrSubstr: "already a configured model",
		},
		{
			name:          "auto alias",
			entrypoint:    DefaultVSRAutoModelName,
			wantErrSubstr: "already an auto-model alias",
		},
	}
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			yamlConfig := recipeTestBaseYAML + `
recipes:
  - name: privacy
    routing:
      decisions:
        - name: privacy_route
          rules:
            operator: AND
            conditions:
              - type: keyword
                name: urgent_keywords
          modelRefs:
            - model: model-b
              use_reasoning: false
entrypoints:
  - model_names: ["` + testCase.entrypoint + `"]
    recipe: privacy
`
			_, err := ParseYAMLBytes([]byte(yamlConfig))
			if err == nil {
				t.Fatalf("expected entrypoint name %q to be rejected", testCase.entrypoint)
			}
			if !strings.Contains(err.Error(), testCase.wantErrSubstr) {
				t.Fatalf("unexpected error: %v", err)
			}
		})
	}
}

func TestEntrypointNameCollidingWithLoRARejected(t *testing.T) {
	yamlConfig := `
version: v0.3
routing:
  modelCards:
    - name: base-model
      loras:
        - name: general-expert
          description: Default LoRA adapter
recipes:
  - name: privacy
    routing:
      decisions:
        - name: privacy_route
          rules:
            operator: AND
            conditions:
              - type: domain
                name: other
          modelRefs:
            - model: base-model
              use_reasoning: false
entrypoints:
  - model_names: ["general-expert"]
    recipe: privacy
providers:
  defaults:
    default_model: base-model
  models:
    - name: base-model
      backend_refs:
        - endpoint: 127.0.0.1:8000
`
	_, err := ParseYAMLBytes([]byte(yamlConfig))
	if err == nil {
		t.Fatal("expected an entrypoint name matching a LoRA adapter to be rejected")
	}
	if !strings.Contains(err.Error(), "already a configured LoRA adapter") {
		t.Fatalf("unexpected error: %v", err)
	}
}
