apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: semantic-router

resources:
  - namespace.yaml
  - pv-models.yaml
  - deployment.yaml
  - service.yaml

# Generate ConfigMap
configMapGenerator:
  - name: semantic-router-config
    files:
      - config.yaml
      - tools_db.json

namespace: vllm-semantic-router-system
