apiVersion: v1
kind: Service
metadata:
  name: semantic-router
  namespace: vllm-semantic-router-system
  labels:
    app: semantic-router
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: classify-api
  selector:
    app: semantic-router
---
apiVersion: v1
kind: Service
metadata:
  name: semantic-router-metrics
  namespace: vllm-semantic-router-system
  labels:
    app: semantic-router
    service: metrics
spec:
  type: ClusterIP
  ports:
  - port: 9190
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: semantic-router
