apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semantic-router.fullname" . }}-config
  namespace: {{ include "semantic-router.namespace" . }}
  labels:
    {{- include "semantic-router.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
  tools_db.json: |
    {{- toJson .Values.toolsDb | nindent 4 }}
