// Package managementapiartifact renders checked client artifacts from the
// canonical Management API registry.
package managementapiartifact

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vllm-project/semantic-router/src/semantic-router/pkg/managementapi"
)

// RenderTypeScriptContract renders transport metadata plus the typed Agent
// client used by browser and custom-console clients. Every emitted shape is
// derived from the same OpenAPI document that is published to API consumers.
func RenderTypeScriptContract() []byte {
	operations := managementapi.Operations()
	document := managementapi.GenerateOpenAPI()
	sort.Slice(operations, func(i, j int) bool {
		return operations[i].OperationID < operations[j].OperationID
	})

	var output strings.Builder
	output.WriteString("// Code generated by tools/management-api-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const MANAGEMENT_API_VERSION = %s\n", tsString(managementapi.APIVersion))
	fmt.Fprintf(&output, "export const MANAGEMENT_API_CONTRACT_VERSION = %s\n", tsString(managementapi.ContractVersion))
	fmt.Fprintf(&output, "export const MANAGEMENT_API_BASE_PATH = %s\n", tsString(managementapi.BasePath))
	fmt.Fprintf(&output, "export const MANAGEMENT_API_MEDIA_TYPE = %s\n\n", tsString(managementapi.JSONMediaType))
	output.WriteString("export const MANAGEMENT_API_HEADERS = {\n")
	fmt.Fprintf(&output, "  namespace: %s,\n", tsString(managementapi.HeaderNamespaceID))
	fmt.Fprintf(&output, "  idempotencyKey: %s,\n", tsString(managementapi.HeaderIdempotencyKey))
	fmt.Fprintf(&output, "  ifMatch: %s,\n", tsString(managementapi.HeaderIfMatch))
	fmt.Fprintf(&output, "  etag: %s,\n", tsString(managementapi.HeaderETag))
	fmt.Fprintf(&output, "  requestId: %s,\n", tsString(managementapi.HeaderRequestID))
	fmt.Fprintf(&output, "  idempotencyReplayed: %s,\n", tsString(managementapi.HeaderIdempotencyReplayed))
	fmt.Fprintf(&output, "  secretResultClaim: %s,\n", tsString(managementapi.HeaderSecretResultClaim))
	output.WriteString("} as const\n\n")

	output.WriteString("export const MANAGEMENT_API_OPERATIONS = {\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "  %s: {\n", operation.OperationID)
		fmt.Fprintf(&output, "    method: %s,\n", tsString(string(operation.Method)))
		fmt.Fprintf(&output, "    path: %s,\n", tsString(operation.Path))
		fmt.Fprintf(&output, "    tag: %s,\n", tsString(operation.Tag))
		fmt.Fprintf(&output, "    scope: %s,\n", tsString(string(operation.Scope)))
		fmt.Fprintf(&output, "    pagination: %s,\n", tsString(string(operation.Pagination)))
		fmt.Fprintf(&output, "    idempotency: %s,\n", tsString(string(operation.Idempotency)))
		fmt.Fprintf(&output, "    revision: %s,\n", tsString(string(operation.Revision)))
		output.WriteString("  },\n")
	}
	output.WriteString("} as const\n\n")

	output.WriteString("export type ManagementApiOperationId = keyof typeof MANAGEMENT_API_OPERATIONS\n")
	output.WriteString("export type ManagementApiMethod =\n")
	output.WriteString("  (typeof MANAGEMENT_API_OPERATIONS)[ManagementApiOperationId]['method']\n\n")
	output.WriteString("type PathParameterNames<Path extends string> =\n")
	output.WriteString("  Path extends `${string}{${infer Parameter}}${infer Rest}`\n")
	output.WriteString("    ? Parameter | PathParameterNames<Rest>\n")
	output.WriteString("    : never\n\n")
	output.WriteString("export type ManagementApiPathParameters<OperationId extends ManagementApiOperationId> = [\n")
	output.WriteString("  PathParameterNames<(typeof MANAGEMENT_API_OPERATIONS)[OperationId]['path']>,\n")
	output.WriteString("] extends [never]\n")
	output.WriteString("  ? never\n")
	output.WriteString("  : Record<\n")
	output.WriteString("      PathParameterNames<(typeof MANAGEMENT_API_OPERATIONS)[OperationId]['path']>,\n")
	output.WriteString("      string | number\n")
	output.WriteString("    >\n\n")
	output.WriteString("type ManagementApiPathArguments<OperationId extends ManagementApiOperationId> = [\n")
	output.WriteString("  ManagementApiPathParameters<OperationId>,\n")
	output.WriteString("] extends [never]\n")
	output.WriteString("  ? []\n")
	output.WriteString("  : [parameters: ManagementApiPathParameters<OperationId>]\n\n")
	output.WriteString("export function managementApiPath<OperationId extends ManagementApiOperationId>(\n")
	output.WriteString("  operationId: OperationId,\n")
	output.WriteString("  ...args: ManagementApiPathArguments<OperationId>\n")
	output.WriteString("): string {\n")
	output.WriteString("  const template = MANAGEMENT_API_OPERATIONS[operationId].path\n")
	output.WriteString("  const parameters = args[0] as Record<string, string | number> | undefined\n")
	output.WriteString("  return template.replace(/\\{([A-Za-z][A-Za-z0-9]*)\\}/g, (_, name: string) => {\n")
	output.WriteString("    const value = parameters?.[name]\n")
	output.WriteString("    if (value === undefined || value === null || String(value).length === 0) {\n")
	output.WriteString("      throw new TypeError(`Missing Management API path parameter: ${name}.`)\n")
	output.WriteString("    }\n")
	output.WriteString("    return encodeURIComponent(String(value))\n")
	output.WriteString("  })\n")
	output.WriteString("}\n")

	renderAgentSchemaTypes(&output, document, operations)
	renderAgentClient(&output, document, operations)

	return []byte(output.String())
}

func tsString(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`'`, `\'`,
		"\r", `\r`,
		"\n", `\n`,
		"\u2028", `\u2028`,
		"\u2029", `\u2029`,
	)
	return "'" + replacer.Replace(value) + "'"
}
