package looper

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"unicode/utf8"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vllm-project/semantic-router/src/semantic-router/pkg/config"
)

func lastNTokensConfig(tokens int) *config.ReMoMAlgorithmConfig {
	return &config.ReMoMAlgorithmConfig{
		CompactionStrategy: "last_n_tokens",
		CompactionTokens:   tokens,
	}
}

// Reproduces the report in issue 3387: a byte-offset cut into CJK text lands
// inside a 3-byte character, so the kept tail is invalid UTF-8 and the JSON
// encoder ships replacement characters to the synthesis model.
func TestCompactResponse_LastNTokensKeepsRuneBoundary(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	content := strings.Repeat("量子计算机的工作原理是", 400)

	out := looper.compactResponse(lastNTokensConfig(1000), content, remomDefaultBytesPerToken)

	require.True(t, utf8.ValidString(out), "compacted text must be valid UTF-8")
	first, _ := utf8.DecodeRuneInString(out)
	assert.NotEqual(t, utf8.RuneError, first, "compacted text must start on a character boundary")
	assert.True(t, strings.HasSuffix(content, out), "compaction keeps the tail")
	assert.LessOrEqual(t, len(out), 1000*4, "advancing to a rune start never exceeds the byte budget")
	assert.Greater(t, len(out), 1000*4-utf8.UTFMax, "at most one partial rune is dropped")

	encoded, err := json.Marshal(out)
	require.NoError(t, err)
	assert.NotContains(t, string(encoded), `�`)
}

func TestCompactResponse_BudgetTracksObservedBytesPerToken(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	cfg := lastNTokensConfig(100)

	ascii := strings.Repeat("abcd", 1000)
	cjk := strings.Repeat("量", 2000)

	// The backend reports 1000 tokens for both responses, so the observed
	// ratios differ (4 bytes per token for ASCII, 3 for CJK) and each keeps
	// 100 tokens' worth of its own script.
	asciiResp := &ModelResponse{Content: ascii, Usage: TokenUsage{CompletionTokens: 1000}}
	cjkResp := &ModelResponse{Content: cjk, Usage: TokenUsage{CompletionTokens: 2000}}

	asciiOut := looper.compactResponse(cfg, ascii, reMoMBytesPerToken(asciiResp))
	cjkOut := looper.compactResponse(cfg, cjk, reMoMBytesPerToken(cjkResp))

	assert.Len(t, asciiOut, 400)
	assert.Len(t, cjkOut, 300)
	assert.Equal(t, 100, utf8.RuneCountInString(cjkOut))
	assert.Equal(t, 100, estimateTokens(asciiOut, reMoMBytesPerToken(asciiResp)))
	assert.Equal(t, 100, estimateTokens(cjkOut, reMoMBytesPerToken(cjkResp)))
}

func TestReMoMBytesPerToken(t *testing.T) {
	tests := []struct {
		name string
		resp *ModelResponse
		want float64
	}{
		{name: "nil response", resp: nil, want: remomDefaultBytesPerToken},
		{name: "no usage reported", resp: &ModelResponse{Content: strings.Repeat("a", 40)}, want: remomDefaultBytesPerToken},
		{name: "usage without generated bytes", resp: &ModelResponse{Usage: TokenUsage{CompletionTokens: 5}}, want: remomDefaultBytesPerToken},
		{
			name: "content only",
			resp: &ModelResponse{Content: strings.Repeat("a", 30), Usage: TokenUsage{CompletionTokens: 10}},
			want: 3,
		},
		{
			name: "content and reasoning share completion usage",
			resp: &ModelResponse{
				Content:          strings.Repeat("a", 30),
				ReasoningContent: strings.Repeat("b", 20),
				Usage:            TokenUsage{CompletionTokens: 10},
			},
			want: 5,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, reMoMBytesPerToken(tc.resp))
		})
	}
}

func TestLastNTokens(t *testing.T) {
	tests := []struct {
		name          string
		content       string
		maxTokens     int
		bytesPerToken float64
		want          string
	}{
		{name: "under budget is unchanged", content: "hello", maxTokens: 10, bytesPerToken: 4, want: "hello"},
		{name: "exact budget is unchanged", content: "abcdefgh", maxTokens: 2, bytesPerToken: 4, want: "abcdefgh"},
		{name: "ascii tail", content: "abcdefghij", maxTokens: 1, bytesPerToken: 4, want: "ghij"},
		{name: "fractional ratio rounds budget up", content: "abcdefghij", maxTokens: 2, bytesPerToken: 2.5, want: "fghij"},
		{name: "cut inside rune advances to next rune", content: "量子计算", maxTokens: 1, bytesPerToken: 4, want: "算"},
		{name: "cut on rune boundary keeps it", content: "量子计算", maxTokens: 2, bytesPerToken: 3, want: "计算"},
		{name: "non-positive ratio falls back to default", content: "abcdefghij", maxTokens: 1, bytesPerToken: 0, want: "ghij"},
		{name: "tiny budget keeps at least one byte", content: "abc", maxTokens: 0, bytesPerToken: 0.1, want: "c"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := lastNTokens(tc.content, tc.maxTokens, tc.bytesPerToken)
			assert.Equal(t, tc.want, got)
			assert.True(t, utf8.ValidString(got))
		})
	}
}

func TestCompactResponse_FullStrategyIsUntouched(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	content := strings.Repeat("量", 5000)
	for _, strategy := range []string{"", "full"} {
		cfg := &config.ReMoMAlgorithmConfig{CompactionStrategy: strategy, CompactionTokens: 1}
		assert.Equal(t, content, looper.compactResponse(cfg, content, 3))
	}
}

func TestBuildReMoMRoundResponse_UsesObservedRatio(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	cfg := lastNTokensConfig(10)
	cjk := strings.Repeat("量", 100)
	resp := &ModelResponse{Model: "m", Content: cjk, Usage: TokenUsage{CompletionTokens: 100}}

	round := looper.buildReMoMRoundResponse(cfg, 1, 1, []*ModelResponse{resp})

	require.Len(t, round.Responses, 1)
	assert.Equal(t, 100, round.Responses[0].TokenCount)
	assert.Equal(t, strings.Repeat("量", 10), round.Responses[0].CompactedContent)
}

// The observed ratio has to reach the prompt the next round actually receives,
// not just the intermediate metadata. Round one returns CJK text billed at
// 3 bytes per token; the synthesis round must see a reference cut at that
// ratio, and it must match the compacted_content published for round one.
func TestReMoMMultiRoundSynthesisPromptUsesObservedRatio(t *testing.T) {
	const (
		compactionTokens = 100
		roundOneTokens   = 2000
	)
	// One 3-byte rune per billed token, so the observed ratio is 3 bytes/token.
	roundOneContent := strings.Repeat("量", roundOneTokens)
	wantReference := strings.Repeat("量", compactionTokens)

	var mu sync.Mutex
	var synthesisPrompts []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		payload := decodeReMoMTestRequest(t, r)
		switch payload.Model {
		case "model-a":
			writeReMoMTestCompletionWithReasoning(t, w, payload.Model, roundOneContent, "", TokenUsage{
				PromptTokens:     10,
				CompletionTokens: roundOneTokens,
				TotalTokens:      roundOneTokens + 10,
			})
		case "model-final":
			mu.Lock()
			synthesisPrompts = append(synthesisPrompts, lastReMoMTestMessageContent(payload))
			mu.Unlock()
			writeReMoMTestCompletion(t, w, payload.Model, "final answer")
		default:
			t.Errorf("unexpected model %q", payload.Model)
		}
	}))
	defer server.Close()

	response, err := NewReMoMLooper(&config.LooperConfig{Endpoint: server.URL}).Execute(
		context.Background(),
		newReMoMTestRequest(&config.ReMoMAlgorithmConfig{
			BreadthSchedule:              []int{1},
			ModelDistribution:            remomDistributionRoundRobin,
			SynthesisModel:               "model-final",
			CompactionStrategy:           "last_n_tokens",
			CompactionTokens:             compactionTokens,
			SynthesisTemplate:            "{{range .ReferenceResponses}}<ref>{{.Content}}</ref>{{end}}",
			IncludeIntermediateResponses: true,
			OnError:                      config.ReMoMOnErrorSkip,
		}, false, []config.ModelRef{{Model: "model-a"}, {Model: "model-final"}}),
	)
	require.NoError(t, err)
	require.Len(t, synthesisPrompts, 1, "expected exactly one synthesis round")

	prompt := synthesisPrompts[0]
	start := strings.Index(prompt, "<ref>")
	end := strings.Index(prompt, "</ref>")
	require.True(t, start >= 0 && end > start, "synthesis prompt is missing the reference markers:\n%s", prompt)
	reference := prompt[start+len("<ref>") : end]

	assert.True(t, utf8.ValidString(reference), "reference sent to the next round must be valid UTF-8")
	assert.Equal(t, wantReference, reference,
		"next-round prompt must be cut at the observed 3 bytes/token (%d runes), not the 4 bytes/token fallback (%d runes)",
		compactionTokens, utf8.RuneCountInString(reference))

	var body struct {
		Rounds []RoundResponse `json:"reasoning_mom_responses"`
	}
	require.NoError(t, json.Unmarshal(response.Body, &body))
	require.Len(t, body.Rounds, 2)
	require.Len(t, body.Rounds[0].Responses, 1)
	assert.Equal(t, body.Rounds[0].Responses[0].CompactedContent, reference,
		"published compacted_content and the reference in the next-round prompt must agree")
}
