package looper

import (
	"encoding/json"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vllm-project/semantic-router/src/semantic-router/pkg/config"
)

func lastNTokensConfig(tokens int) *config.ReMoMAlgorithmConfig {
	return &config.ReMoMAlgorithmConfig{
		CompactionStrategy: "last_n_tokens",
		CompactionTokens:   tokens,
	}
}

// Reproduces the report in issue 3387: a byte-offset cut into CJK text lands
// inside a 3-byte character, so the kept tail is invalid UTF-8 and the JSON
// encoder ships replacement characters to the synthesis model.
func TestCompactResponse_LastNTokensKeepsRuneBoundary(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	content := strings.Repeat("量子计算机的工作原理是", 400)

	out := looper.compactResponse(lastNTokensConfig(1000), content, remomDefaultBytesPerToken)

	require.True(t, utf8.ValidString(out), "compacted text must be valid UTF-8")
	first, _ := utf8.DecodeRuneInString(out)
	assert.NotEqual(t, utf8.RuneError, first, "compacted text must start on a character boundary")
	assert.True(t, strings.HasSuffix(content, out), "compaction keeps the tail")
	assert.LessOrEqual(t, len(out), 1000*4, "advancing to a rune start never exceeds the byte budget")
	assert.Greater(t, len(out), 1000*4-utf8.UTFMax, "at most one partial rune is dropped")

	encoded, err := json.Marshal(out)
	require.NoError(t, err)
	assert.NotContains(t, string(encoded), `�`)
}

func TestCompactResponse_BudgetTracksObservedBytesPerToken(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	cfg := lastNTokensConfig(100)

	ascii := strings.Repeat("abcd", 1000)
	cjk := strings.Repeat("量", 2000)

	// The backend reports 1000 tokens for both responses, so the observed
	// ratios differ (4 bytes per token for ASCII, 3 for CJK) and each keeps
	// 100 tokens' worth of its own script.
	asciiResp := &ModelResponse{Content: ascii, Usage: TokenUsage{CompletionTokens: 1000}}
	cjkResp := &ModelResponse{Content: cjk, Usage: TokenUsage{CompletionTokens: 2000}}

	asciiOut := looper.compactResponse(cfg, ascii, reMoMBytesPerToken(asciiResp))
	cjkOut := looper.compactResponse(cfg, cjk, reMoMBytesPerToken(cjkResp))

	assert.Equal(t, 400, len(asciiOut))
	assert.Equal(t, 300, len(cjkOut))
	assert.Equal(t, 100, utf8.RuneCountInString(cjkOut))
	assert.Equal(t, 100, estimateTokens(asciiOut, reMoMBytesPerToken(asciiResp)))
	assert.Equal(t, 100, estimateTokens(cjkOut, reMoMBytesPerToken(cjkResp)))
}

func TestReMoMBytesPerToken(t *testing.T) {
	tests := []struct {
		name string
		resp *ModelResponse
		want float64
	}{
		{name: "nil response", resp: nil, want: remomDefaultBytesPerToken},
		{name: "no usage reported", resp: &ModelResponse{Content: strings.Repeat("a", 40)}, want: remomDefaultBytesPerToken},
		{name: "usage without generated bytes", resp: &ModelResponse{Usage: TokenUsage{CompletionTokens: 5}}, want: remomDefaultBytesPerToken},
		{
			name: "content only",
			resp: &ModelResponse{Content: strings.Repeat("a", 30), Usage: TokenUsage{CompletionTokens: 10}},
			want: 3,
		},
		{
			name: "content and reasoning share completion usage",
			resp: &ModelResponse{
				Content:          strings.Repeat("a", 30),
				ReasoningContent: strings.Repeat("b", 20),
				Usage:            TokenUsage{CompletionTokens: 10},
			},
			want: 5,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, reMoMBytesPerToken(tc.resp))
		})
	}
}

func TestLastNTokens(t *testing.T) {
	tests := []struct {
		name          string
		content       string
		maxTokens     int
		bytesPerToken float64
		want          string
	}{
		{name: "under budget is unchanged", content: "hello", maxTokens: 10, bytesPerToken: 4, want: "hello"},
		{name: "exact budget is unchanged", content: "abcdefgh", maxTokens: 2, bytesPerToken: 4, want: "abcdefgh"},
		{name: "ascii tail", content: "abcdefghij", maxTokens: 1, bytesPerToken: 4, want: "ghij"},
		{name: "fractional ratio rounds budget up", content: "abcdefghij", maxTokens: 2, bytesPerToken: 2.5, want: "fghij"},
		{name: "cut inside rune advances to next rune", content: "量子计算", maxTokens: 1, bytesPerToken: 4, want: "算"},
		{name: "cut on rune boundary keeps it", content: "量子计算", maxTokens: 2, bytesPerToken: 3, want: "计算"},
		{name: "non-positive ratio falls back to default", content: "abcdefghij", maxTokens: 1, bytesPerToken: 0, want: "ghij"},
		{name: "tiny budget keeps at least one byte", content: "abc", maxTokens: 0, bytesPerToken: 0.1, want: "c"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := lastNTokens(tc.content, tc.maxTokens, tc.bytesPerToken)
			assert.Equal(t, tc.want, got)
			assert.True(t, utf8.ValidString(got))
		})
	}
}

func TestCompactResponse_FullStrategyIsUntouched(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	content := strings.Repeat("量", 5000)
	for _, strategy := range []string{"", "full"} {
		cfg := &config.ReMoMAlgorithmConfig{CompactionStrategy: strategy, CompactionTokens: 1}
		assert.Equal(t, content, looper.compactResponse(cfg, content, 3))
	}
}

func TestBuildReMoMRoundResponse_UsesObservedRatio(t *testing.T) {
	looper := NewReMoMLooper(&config.LooperConfig{})
	cfg := lastNTokensConfig(10)
	cjk := strings.Repeat("量", 100)
	resp := &ModelResponse{Model: "m", Content: cjk, Usage: TokenUsage{CompletionTokens: 100}}

	round := looper.buildReMoMRoundResponse(cfg, 1, 1, []*ModelResponse{resp})

	require.Len(t, round.Responses, 1)
	assert.Equal(t, 100, round.Responses[0].TokenCount)
	assert.Equal(t, strings.Repeat("量", 10), round.Responses[0].CompactedContent)
}
