apiVersion: v1
kind: Service
metadata:
  name: provider-mocker
  namespace: default
spec:
  selector:
    app: provider-mocker
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
